import json,math
from pathlib import Path
from playwright.sync_api import sync_playwright
from browser_support import load,ROOT
(ROOT/'previews').mkdir(exist_ok=True)
(ROOT/'docs').mkdir(exist_ok=True)
checks=[]
def check(name,passed,detail=None):
 checks.append({'name':name,'pass':bool(passed),'detail':detail});print(('PASS ' if passed else 'FAIL ')+name,flush=True)
with sync_playwright() as p:
 b=p.chromium.launch(executable_path='/usr/bin/chromium',headless=False,args=['--no-sandbox','--enable-webgl','--ignore-gpu-blocklist','--disable-dev-shm-usage'])
 page=b.new_page(viewport={'width':1440,'height':900});errors=[];page.on('pageerror',lambda e:errors.append(str(e)));page.on('console',lambda m:errors.append(m.text) if m.type=='error' else None)
 load(page);page.wait_for_timeout(500)
 check('WebGL2 initialized',page.evaluate('!!window.__BRAAZA__'))
 check('linear HDR framebuffer active',page.evaluate('window.__BRAAZA__.inspect().hdr'))
 s=page.evaluate('window.__BRAAZA__.inspect()');check('four independent 3D panels',len(s['cards'])==4)
 page.mouse.move(720,420);page.mouse.wheel(0,440);page.wait_for_timeout(1400)
 state=page.evaluate('window.__BRAAZA__.inspect()');check('wheel raises conveyor',state['position']>.35);check('chains travel in opposite directions',state['chains'][0]>0 and state['chains'][1]<0)
 page.mouse.down();page.mouse.move(720,250,steps=10);page.mouse.up();page.wait_for_timeout(900)
 check('drag moves conveyor without opening modal',page.evaluate('!document.querySelector("#viewer").open && window.__BRAAZA__.inspect().position>1'))
 check('drag produces no text selection',page.evaluate('String(window.getSelection())===""'))
 page.locator('#scene').focus();page.keyboard.press('Home');page.wait_for_timeout(150)
 check('Home restores gallery',abs(page.evaluate('window.__BRAAZA__.inspect().position'))<.02)
 page.keyboard.press('ArrowDown');page.wait_for_timeout(1100);check('keyboard navigation',page.evaluate('window.__BRAAZA__.inspect().position')>.8)
 page.keyboard.press('Enter');page.wait_for_timeout(300);check('Enter opens accessible media dialog',page.locator('#viewer').evaluate('(e)=>e.open'))
 check('demo is explicitly labeled in detail',page.locator('#viewer-content').inner_text().find('demonstra')>=0 or page.locator('#viewer-content').inner_text().find('procedural')>=0 or page.locator('#viewer-content').inner_text().find('Prévia')>=0)
 page.keyboard.press('Escape');check('Escape closes and restores keyboard target',page.evaluate('!document.querySelector("#viewer").open && document.activeElement.id==="scene"'))
 page.locator('#quality').click();check('low quality selectable',page.evaluate('window.__BRAAZA__.inspect().quality')=='low')
 page.locator('#quality').click();page.locator('#quality').click()
 page.locator('#pause').click();t=page.evaluate('window.__BRAAZA__.get().time');page.wait_for_timeout(450);check('animation pause freezes clock',page.evaluate('window.__BRAAZA__.get().time')==t);page.locator('#pause').click()
 page.locator('#scene').focus();page.keyboard.press('Home');page.wait_for_timeout(1400);page.mouse.move(1400,850);page.screenshot(path=str(ROOT/'previews/desktop.png'))
 # Audit every HDR pixel, not only gl.getError(). This catches non-finite bloom propagation.
 finite=page.evaluate('''()=>{const f=window.__BRAAZA__.get(),g=f.gl;f.render();return [f.sceneTarget,...f.blooms.flat()].map(t=>{f.setTarget(t);const b=new Float32Array(t.w*t.h*4);g.readPixels(0,0,t.w,t.h,g.RGBA,g.FLOAT,b);let bad=0,max=0;for(let i=0;i<b.length;i++){if(!Number.isFinite(b[i]))bad++;else max=Math.max(max,b[i]);}return {bad,max};});}''')
 check('all HDR and bloom pixels finite',all(t['bad']==0 for t in finite),finite)
 check('no WebGL errors',page.evaluate('window.__BRAAZA__.get().gl.getError()')==0)
 # Pointer lands on an actual projected panel and returns its index.
 pos=page.evaluate('window.__BRAAZA__.inspect().cards[1].screen');page.mouse.move(*pos);page.wait_for_timeout(400)
 check('raycast hover picks visible panel',page.evaluate('window.__BRAAZA__.inspect().hover')==1)
 page.screenshot(path=str(ROOT/'previews/hover.png'));page.mouse.click(*pos);check('click opens selected panel',page.locator('#viewer').evaluate('(e)=>e.open'));page.keyboard.press('Escape')
 page.emulate_media(reduced_motion='reduce');page.wait_for_timeout(350);t=page.evaluate('window.__BRAAZA__.get().time');page.wait_for_timeout(400);check('reduced motion stops autonomous animation',page.evaluate('window.__BRAAZA__.get().time')==t)
 check('no JavaScript or shader errors',not errors,errors)
 page.close()
 mobile=b.new_page(viewport={'width':390,'height':844},device_scale_factor=1,is_mobile=True,has_touch=True);load(mobile);mobile.wait_for_timeout(900)
 check('mobile WebGL2 initialized',mobile.evaluate('!!window.__BRAAZA__'))
 check('mobile has no horizontal overflow',mobile.evaluate('document.documentElement.scrollWidth<=innerWidth'))
 mobile.screenshot(path=str(ROOT/'previews/mobile.png'))
 client=mobile.context.new_cdp_session(mobile)
 client.send('Input.dispatchTouchEvent',{'type':'touchStart','touchPoints':[{'x':192,'y':550}]})
 for y in [520,480,430,390,340]:client.send('Input.dispatchTouchEvent',{'type':'touchMove','touchPoints':[{'x':192,'y':y}]})
 client.send('Input.dispatchTouchEvent',{'type':'touchEnd','touchPoints':[]});mobile.wait_for_timeout(1100)
 check('touch drag moves gallery and does not open a card',mobile.evaluate('window.__BRAAZA__.inspect().position>.5 && !document.querySelector("#viewer").open'))
 mobile.locator('#gallery').tap();check('gallery button works on touch',mobile.locator('#viewer').evaluate('(e)=>e.open'));mobile.locator('#close').tap()
 check('mobile scroll and hitboxes remain inside viewport',mobile.evaluate('window.__BRAAZA__.inspect().cards.every(c=>c.screen[0]>0 && c.screen[0]<innerWidth)'))
 b.close()
(ROOT/'docs/browser-tests.json').write_text(json.dumps(checks,indent=2));print('TOTAL',len(checks),'FAILED',sum(not c['pass'] for c in checks));raise SystemExit(0 if all(c['pass'] for c in checks) else 1)
