import json,os,math
from playwright.sync_api import sync_playwright
from support import load,ROOT
checks=[]
def check(name,ok,detail=None):
 checks.append(dict(name=name,passed=bool(ok),detail=detail));print(('PASS ' if ok else 'FAIL ')+name,flush=True)
with sync_playwright() as pw:
 b=pw.chromium.launch(executable_path='/usr/bin/chromium',headless=False,args=['--no-sandbox','--enable-webgl','--ignore-gpu-blocklist','--disable-dev-shm-usage'])
 page=b.new_page(viewport={'width':1440,'height':900});errors=[]
 page.on('pageerror',lambda e:errors.append(str(e)));page.on('console',lambda m: errors.append(m.text) if m.type=='error' else None)
 load(page);page.wait_for_timeout(400)
 check('WebGL2 ready',page.evaluate('!!window.__BRAAZA__'))
 check('four media cards preserved',page.evaluate('window.__BRAAZA__.get().cards.length===4'))
 page.mouse.move(100,600);page.locator('#scene').focus();page.keyboard.press('Home');page.wait_for_timeout(500)
 page.evaluate('''()=>{const f=window.__BRAAZA__.get();f.paused=true;f.time=3;f.clear();for(let i=0;i<80;i++)f.update(.016);f.render();}''')
 page.screenshot(path=str(ROOT/'previews/desktop.png'))
 page.evaluate('window.__BRAAZA__.get().paused=false')
 page.mouse.move(720,440);page.mouse.wheel(0,440);page.wait_for_timeout(1100)
 s=page.evaluate('window.__BRAAZA__.inspect()');check('wheel raises the gallery',s['position']>.4);check('chains have opposing velocities',s['chains'][0]>0 and s['chains'][1]<0)
 page.mouse.down();page.mouse.move(720,250,steps=12);page.mouse.up();page.wait_for_timeout(700)
 check('drag advances without opening viewer',page.evaluate('window.__BRAAZA__.inspect().position>1 && !document.querySelector("#viewer").open'))
 check('no selected text after drag',page.evaluate('String(getSelection())===""'))
 page.locator('#scene').focus();page.keyboard.press('Home');page.wait_for_function('Math.abs(window.__BRAAZA__.get().cards[1].y-4.1)<.0001',timeout=20000)
 check('Home resets gallery and chain travel',page.evaluate('window.__BRAAZA__.get().motion.value===0 && window.__BRAAZA__.get().motion.travel===0'))
 page.keyboard.press('ArrowDown');page.wait_for_function('window.__BRAAZA__.inspect().position>.95',timeout=20000);check('keyboard navigation moves gallery',page.evaluate('window.__BRAAZA__.inspect().position>.9'))
 page.keyboard.press('Enter');page.wait_for_timeout(200);check('keyboard opens dialog',page.locator('#viewer').evaluate('(e)=>e.open'))
 check('preview media decodes successfully',page.locator('#viewer img').evaluate('(e)=>e.complete&&e.naturalWidth>0'))
 check('demo is not attributed as real work', 'demonstra' in page.locator('#viewer-content').inner_text().lower() or 'procedural' in page.locator('#viewer-content').inner_text().lower())
 page.keyboard.press('Escape');check('Escape restores scene focus',page.evaluate('!document.querySelector("#viewer").open&&document.activeElement.id==="scene"'))
 page.keyboard.press('Home');page.wait_for_function('Math.abs(window.__BRAAZA__.get().cards[1].y-4.1)<.0001',timeout=20000)
 pos=page.evaluate('window.__BRAAZA__.inspect().cards[1].screen');page.mouse.move(pos[0]-85,pos[1]+10,steps=5);page.mouse.move(pos[0]+45,pos[1]-10,steps=10);page.wait_for_timeout(180)
 check('raycast selects intended card',page.evaluate('window.__BRAAZA__.inspect().hover===1'))
 check('cursor injects a dissipating heat trail',page.evaluate('window.__BRAAZA__.get().cards[1].trails.some((v,i)=>i%4===3&&v>0)'))
 page.screenshot(path=str(ROOT/'previews/hover.png'));page.mouse.click(*pos);page.wait_for_timeout(150);check('click opens the pointed card',page.locator('#viewer').evaluate('(e)=>e.open'));page.keyboard.press('Escape')
 for quality in ['low','high','auto']:
  page.locator('#quality').click();page.wait_for_timeout(160)
  check(quality+' quality resizes render targets',page.evaluate('window.__BRAAZA__.inspect().quality')==quality)
 check('quality changes preserve valid framebuffers',page.evaluate('window.__BRAAZA__.get().gl.getError()')==0)
 page.locator('#pause').click();t=page.evaluate('window.__BRAAZA__.get().time');page.wait_for_timeout(300);check('pause freezes procedural animation',page.evaluate('window.__BRAAZA__.get().time')==t);page.locator('#pause').click()
 # Sweep phase continuously, including each wrap. Check full coverage on the scene range.
 coverage=page.evaluate('''()=>{const f=window.__BRAAZA__.get();let worst=0;for(let phase=-25;phase<=25;phase+=.137)for(const side of [-1,1])for(const secondary of [false,true]){const ys=f.chains.filter(l=>l.side===side&&l.secondary===secondary).map(l=>f.linkPose(l,phase).pos[1]).sort((a,b)=>a-b);if(ys[0]>-9||ys.at(-1)<29)return false;for(let i=1;i<ys.length;i++)worst=Math.max(worst,ys[i]-ys[i-1]);}return worst<.880001;}''')
 check('chain coverage stays continuous across 365 phase samples',coverage)
 for phase in [.7,2.9,7.2]:
  page.evaluate('''t=>{const f=window.__BRAAZA__.get();f.motion.value=t;f.motion.target=t;f.update(0);f.render();}''',phase)
  page.screenshot(path=str(ROOT/f'previews/scroll-{phase}.png'))
 check('scroll sweep has no WebGL errors',page.evaluate('window.__BRAAZA__.get().gl.getError()')==0)
 page.emulate_media(reduced_motion='reduce');page.wait_for_timeout(180);t=page.evaluate('window.__BRAAZA__.get().time');page.wait_for_timeout(220);check('reduced motion freezes noise and emitters',page.evaluate('window.__BRAAZA__.get().time')==t)
 page.emulate_media(reduced_motion='no-preference');page.wait_for_timeout(100)
 check('no JavaScript or shader errors on desktop',not errors,errors)
 page.close()
 mobile=b.new_page(viewport={'width':390,'height':844},device_scale_factor=1,is_mobile=True,has_touch=True);mobileErrors=[];mobile.on('pageerror',lambda e:mobileErrors.append(str(e)));load(mobile);mobile.wait_for_timeout(400)
 check('mobile initializes WebGL2',mobile.evaluate('!!window.__BRAAZA__'))
 check('mobile has no horizontal overflow',mobile.evaluate('document.documentElement.scrollWidth<=innerWidth'))
 mobile.screenshot(path=str(ROOT/'previews/mobile.png'))
 c=mobile.context.new_cdp_session(mobile);c.send('Input.dispatchTouchEvent',{'type':'touchStart','touchPoints':[{'x':190,'y':550}]})
 for y in [520,480,440,400,340]:c.send('Input.dispatchTouchEvent',{'type':'touchMove','touchPoints':[{'x':190,'y':y}]})
 c.send('Input.dispatchTouchEvent',{'type':'touchEnd','touchPoints':[]});mobile.wait_for_timeout(900)
 check('mobile swipe advances without accidental click',mobile.evaluate('window.__BRAAZA__.inspect().position>.5&&!document.querySelector("#viewer").open'))
 mobile.locator('#gallery').tap();check('mobile gallery navigation works',mobile.locator('#viewer').evaluate('(e)=>e.open'));mobile.locator('#close').tap()
 check('mobile media remains centered',mobile.evaluate('window.__BRAAZA__.inspect().cards.every(c=>c.screen[0]>0&&c.screen[0]<innerWidth)'))
 check('no mobile JS or WebGL errors',not mobileErrors and mobile.evaluate('window.__BRAAZA__.get().gl.getError()')==0,mobileErrors)
 b.close()
(ROOT/'docs/browser.json').write_text(json.dumps(checks,indent=2));print('TOTAL',len(checks),'FAIL',sum(not c['passed'] for c in checks));raise SystemExit(0 if all(c['passed'] for c in checks) else 1)
