import {compose,transform,invert} from '../math.js';
import {rock,cube,panel,tube} from '../geometry.js';
export {rock,cube,panel,tube};
const empty=()=>({positions:[],normals:[],uvs:[],indices:[]});
export function validateGeometry(g){if(!g||g.positions.length%3||g.normals.length!==g.positions.length||g.uvs.length!==g.positions.length/3*2||g.indices.length%3)throw Error('Invalid geometry layout');if(![...g.positions,...g.normals,...g.uvs].every(Number.isFinite)||!g.indices.every(i=>Number.isInteger(i)&&i>=0&&i<g.positions.length/3))throw Error('Invalid geometry value/index');return true;}
export function face(d,points,uvs=null){const[a,b,c]=points,ab=b.map((v,i)=>v-a[i]),ac=c.map((v,i)=>v-a[i]);let n=[ab[1]*ac[2]-ab[2]*ac[1],ab[2]*ac[0]-ab[0]*ac[2],ab[0]*ac[1]-ab[1]*ac[0]],len=Math.hypot(...n);if(len<1e-8)return;n=n.map(v=>v/len);const start=d.positions.length/3;points.forEach((p,i)=>{d.positions.push(...p);d.normals.push(...n);d.uvs.push(...(uvs?.[i]??[p[0]/4.8+.5,p[1]/2.25+.5]));});for(let i=1;i<points.length-1;i++)d.indices.push(start,start+i,start+i+1);}
/** Closed thick rounded crystal. UVs stay attached to the media plane. */
export function crystal(w=4.8,h=2.25,depth=.31){const d=empty(),outline=[],r=.105;for(let corner=0;corner<4;corner++)for(let j=0;j<8;j++){const a=(corner+j/8)*Math.PI/2,cx=(corner===0||corner===3?1:-1)*(w/2-r),cy=(corner<2?1:-1)*(h/2-r);outline.push([cx+r*Math.cos(a),cy+r*Math.sin(a)]);}const rings=[[.970,0],[1,-.073],[1,-depth+.068],[.970,-depth]],loop=layer=>outline.map(([x,y])=>[x*rings[layer][0],y*rings[layer][0],rings[layer][1]]),front=loop(0),back=loop(3);for(let i=0;i<outline.length;i++){const j=(i+1)%outline.length;face(d,[[0,0,0],front[i],front[j]]);face(d,[[0,0,-depth],back[j],back[i]]);for(let layer=0;layer<3;layer++){const a=loop(layer),b=loop(layer+1);face(d,[a[i],b[i],b[j],a[j]]);}}return d;}
export function arch(radius=2.2,thickness=.46,depth=.65,segments=24,pointed=.3){const d=empty();for(let i=0;i<segments;i++){const a=i/segments*Math.PI,b=(i+1)/segments*Math.PI,xy=(angle,r)=>[Math.cos(angle)*r,Math.sin(angle)*r*(1+pointed)],ia=xy(a,radius),ib=xy(b,radius),oa=xy(a,radius+thickness),ob=xy(b,radius+thickness),f=[...ia,depth],g=[...ib,depth],h=[...ob,depth],k=[...oa,depth],F=[...ia,-depth],G=[...ib,-depth],H=[...ob,-depth],K=[...oa,-depth];face(d,[f,k,h,g]);face(d,[F,G,H,K]);face(d,[f,g,G,F]);face(d,[k,K,H,h]);if(i===0)face(d,[f,F,K,k]);if(i===segments-1)face(d,[g,h,H,G]);}return d;}
export function column(sides=8,taper=.85){const d=empty();for(let i=0;i<sides;i++){const a=i/sides*Math.PI*2,b=(i+1)/sides*Math.PI*2,p=[Math.cos(a),-1,Math.sin(a)],q=[Math.cos(b),-1,Math.sin(b)],r=[Math.cos(b)*taper,1,Math.sin(b)*taper],s=[Math.cos(a)*taper,1,Math.sin(a)*taper];face(d,[p,s,r,q]);face(d,[[0,-1,0],p,q]);face(d,[[0,1,0],r,s]);}return d;}
export function spire(sides=5){const d=empty();for(let i=0;i<sides;i++){const a=i/sides*Math.PI*2,b=(i+1)/sides*Math.PI*2,p=[Math.cos(a),-1,Math.sin(a)],q=[Math.cos(b),-1,Math.sin(b)];face(d,[p,[.1,1.4,-.05],q]);face(d,[[0,-1,0],p,q]);}return d;}
export function banner(){const d=empty(),nx=6,ny=18;for(let y=0;y<=ny;y++)for(let x=0;x<=nx;x++){const u=x/nx,v=y/ny;d.positions.push((u-.5)*2,v*2-1+Math.abs(u-.5)*.24*(1-v),Math.sin(u*7)*.025);d.normals.push(0,0,1);d.uvs.push(u,v);}for(let y=0;y<ny;y++)for(let x=0;x<nx;x++){const a=y*(nx+1)+x,b=a+nx+1;d.indices.push(a,a+1,b+1,a,b+1,b);}return d;}
export function emblem(){const d=empty(),p=[[.06,1,0],[.56,.15,0],[.12,-.52,0],[.16,.04,0],[-.25,.21,0],[-.52,-.28,0],[-.52,.26,0]];for(let i=1;i<p.length-1;i++)face(d,[p[0],p[i+1],p[i]]);return d;}
export function combine(items,geometry){const d={...empty(),surfaces:[]};for(const item of items){const g=geometry[item.mesh];if(!g)throw Error('Unknown mesh '+item.mesh);const m=item.model,inv=invert(m),start=d.positions.length/3;for(let i=0;i<g.positions.length;i+=3){const p=transform(m,[...g.positions.slice(i,i+3),1]);d.positions.push(...p.slice(0,3));const n=g.normals.slice(i,i+3),normal=[inv[0]*n[0]+inv[1]*n[1]+inv[2]*n[2],inv[4]*n[0]+inv[5]*n[1]+inv[6]*n[2],inv[8]*n[0]+inv[9]*n[1]+inv[10]*n[2]],l=Math.hypot(...normal);d.normals.push(...normal.map(v=>v/l));d.surfaces.push(...item.surface);}d.uvs.push(...g.uvs);for(const i of g.indices)d.indices.push(start+i);}return d;}
export function model(pos=[0,0,0],rot=[0,0,0],scale=[1,1,1]){const m=compose(pos,rot);if(!Array.isArray(scale))scale=[scale,scale,scale];for(let c=0;c<3;c++)for(let r=0;r<4;r++)m[c*4+r]*=scale[c];return m;}
/** Fluted masonry shaft with collars built into its silhouette. */
export function carvedColumn(sides=24){const d=empty(),profile=[[-1,1.04],[-.96,1.04],[-.925,.94],[-.88,.91],[-.84,.84],[-.80,.81],[-.42,.795],[-.405,.87],[-.38,.87],[-.355,.78],[.15,.76],[.17,.83],[.20,.83],[.22,.755],[.82,.73],[.85,.78],[.88,.79],[.90,.91],[.945,.96],[1,.96]];const ring=(j,i)=>{const a=i/sides*Math.PI*2,[y,r]=profile[j],rib=.96+.04*Math.cos(a*8);return [Math.cos(a)*r*rib,y,Math.sin(a)*r*rib];};for(let j=0;j<profile.length-1;j++)for(let i=0;i<sides;i++)face(d,[ring(j,i),ring(j+1,i),ring(j+1,(i+1)%sides),ring(j,(i+1)%sides)]);for(let i=0;i<sides;i++){face(d,[[0,-1,0],ring(0,i),ring(0,(i+1)%sides)]);face(d,[[0,1,0],ring(profile.length-1,(i+1)%sides),ring(profile.length-1,i)]);}return d;}
/** Chamfered cuboid, defined by its six faces, twelve edges and eight corners. */
export function beveledBox(b=.09){const d=empty(),a=1-b;const orient=p=>{const ab=p[1].map((v,i)=>v-p[0][i]),ac=p[2].map((v,i)=>v-p[0][i]),n=[ab[1]*ac[2]-ab[2]*ac[1],ab[2]*ac[0]-ab[0]*ac[2],ab[0]*ac[1]-ab[1]*ac[0]];if(n.reduce((s,v,i)=>s+v*p[0][i],0)<0)p.reverse();face(d,p);};for(let axis=0;axis<3;axis++)for(const sign of[-1,1]){const other=[0,1,2].filter(i=>i!==axis),p=[];for(const[u,v]of[[-1,-1],[1,-1],[1,1],[-1,1]]){const q=[0,0,0];q[axis]=sign;q[other[0]]=u*a;q[other[1]]=v*a;p.push(q);}orient(p);}for(let axis=0;axis<3;axis++)for(const s of[-1,1])for(const t of[-1,1]){const o=[0,1,2].filter(i=>i!==axis),p=[];for(const[z,sw]of[[-a,0],[a,0],[a,1],[-a,1]]){const q=[0,0,0];q[axis]=z;q[o[0]]=s*(sw?a:1);q[o[1]]=t*(sw?1:a);p.push(q);}orient(p);}for(const x of[-1,1])for(const y of[-1,1])for(const z of[-1,1])orient([[x,y*a,z*a],[x*a,y,z*a],[x*a,y*a,z]]);return d;}
