/** Browser checks against the actual volumetric scene, not its screenshot fallback. */
const {chromium}=require('playwright');const fs=require('node:fs');const path=require('node:path');
const BASE=process.env.DXT_BASE_URL||'http://127.0.0.1:3000',OUT=process.env.DXT_TEST_OUT||path.resolve('previews');fs.mkdirSync(OUT,{recursive:true});
const checks=[],errors=[];function check(name,pass,data){checks.push({name,pass:!!pass,data});console.log((pass?'PASS ':'FAIL ')+name);if(!pass)throw Error(name+' '+JSON.stringify(data));}
async function ready(p,kind='hero'){await p.waitForFunction(t=>{let s=window.__DXT__?.inspect().scene;return s&&s.frames>0&&(t==='hero'?s.geometry==='real volumetric meshes':s.type==='glb-mesh')},kind,{polling:100,timeout:60000});}
(async()=>{const browser=await chromium.launch({headless:true,args:['--no-sandbox','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
const p=await browser.newPage({viewport:{width:1440,height:900}});p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error'&&!m.text().includes('favicon'))errors.push(m.text());});
await p.addInitScript(()=>localStorage.setItem('dxt-settings',JSON.stringify({quality:'auto',paused:true})));
await p.goto(BASE+'/?debug',{waitUntil:'load'});await ready(p);
check('hero uses a real WebGL2 renderer',await p.evaluate(()=>__DXT__.scene().gl instanceof WebGL2RenderingContext));
check('two independent volumetric car models',await p.evaluate(()=>{const s=__DXT__.scene();return s.cars.length===2&&s.cars.every(c=>c.userData.authored&&c.userData.geometryMode==='volumetric');}));
check('real reflection target and multiple lighting/shadow passes',await p.evaluate(()=>{const s=__DXT__.scene();return s.ground.isReflector&&s.key.castShadow&&s.renderer.info.render.calls>10;}));
check('no fake depth-mapped car planes',await p.evaluate(()=>{const s=__DXT__.scene();return !s.image&&!s.depth&&s.inspect().carTriangles>30000;}));
check('hero has no GL errors',await p.evaluate(()=>__DXT__.scene().gl.getError()===0));
check('diagonal editorial bands replace the rejected dashboard',await p.locator('.ribbon').count()===2&&await p.locator('.bio-ribbon').count()===1);
check('diagonal strips use actual clip paths',await p.locator('.ribbon-fill').evaluateAll(es=>es.every(e=>getComputedStyle(e).clipPath.startsWith('polygon'))));
check('every group logo belongs to the supplied groups',await p.locator('.ribbon-groups img').evaluateAll(es=>es.some(e=>e.src.includes('revline'))&&es.some(e=>e.src.includes('frost'))));
check('header/footer dimensions remain restrained',await p.evaluate(()=>document.querySelector('#header').offsetHeight<85&&document.querySelector('#footer').offsetHeight<85));
check('Berserk CTA preserves the supplied place',await p.locator('.hero-actions a.primary').getAttribute('href')==='https://www.roblox.com/pt/games/136449173422746/BERSERK-DRIFT-X-WIP');
const geometry=await p.locator('.hero').boundingBox();check('hero retains the reference wide aspect and first-screen prominence',geometry.height>300&&geometry.height<410,geometry);
await p.screenshot({path:path.join(OUT,'desktop.png'),fullPage:true});
const yaw=await p.evaluate(()=>__DXT__.scene().targetYaw);await p.mouse.move(880,260);await p.mouse.down();await p.mouse.move(1050,278,{steps:7});await p.mouse.up();await p.waitForTimeout(600);
check('drag rotates the physical camera, not a texture',await p.evaluate(a=>Math.abs(__DXT__.scene().yaw-a)>.35,yaw));check('drag releases its captured pointer',await p.evaluate(()=>__DXT__.scene().drag===null));
await p.locator('#reset-view').click();await p.waitForFunction(()=>Math.abs(__DXT__.scene().yaw+.72)<.035,null,{polling:100,timeout:20000});check('reset restores reference yaw',await p.evaluate(()=>Math.abs(__DXT__.scene().yaw+.72)<.035));
await p.locator('#expand-view').click();await p.waitForTimeout(350);check('expanded 3D viewer fills viewport',await p.locator('.hero').evaluate(e=>{let b=e.getBoundingClientRect();return b.width===innerWidth&&b.height===innerHeight;}));
await p.locator('#hero-canvas').focus();await p.keyboard.press('ArrowLeft');check('3D view has keyboard controls',await p.evaluate(()=>__DXT__.scene().targetYaw>-.7));await p.keyboard.press('Escape');check('Escape restores the editorial page',await p.evaluate(()=>!__DXT__.scene().expanded&&!document.body.classList.contains('viewing-car')));
await p.locator('#reset-view').click();
await p.locator('#quality').click();await p.waitForTimeout(300);check('low quality reduces render pixels',await p.evaluate(()=>__DXT__.inspect().settings.quality==='low'&&__DXT__.scene().renderer.getPixelRatio()<=.8));
await p.locator('#quality').click();check('high quality remains explicitly selectable',await p.evaluate(()=>__DXT__.inspect().settings.quality==='high'));await p.locator('#quality').click();
for(const r of['groups','projects','about','contact']){
 await p.locator(`header nav a[href="/${r}"]`).click();await p.waitForFunction(r=>__DXT__.inspect().route===r,r,{polling:100});
 check(r+' retains its dedicated route',new URL(p.url()).pathname==='/'+r);check(r+' has one primary heading',await p.locator('main h1').count()===1);check(r+' active navigation is unique',await p.locator('nav [aria-current="page"]').count()===1);check(r+' fits desktop',await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 if(r==='about'){await ready(p,'logo');check('About retains the provided GLB geometry',await p.evaluate(()=>__DXT__.inspect().scene.triangles===3104));check('logo shader still compiles',await p.evaluate(()=>__DXT__.scene().gl.getError()===0));await p.screenshot({path:path.join(OUT,'about.png'),fullPage:true});}
}
check('actual social destinations only',await p.locator('.contact-row').count()===4);check('no fabricated email/metrics',await p.evaluate(()=>!document.querySelector('a[href^="mailto:"]')&&!/100K\+|1\.2M\+|50\+ CARS/.test(document.body.innerText)));check('external links have opener protection',await p.locator('a[target="_blank"]').evaluateAll(es=>es.every(e=>e.rel.includes('noopener'))));
const el=p.locator('.contact-row').first(),bb=await el.boundingBox();await p.mouse.move(bb.x+100,bb.y+30);await p.waitForTimeout(100);const early=await el.evaluate(e=>+e.style.getPropertyValue('--glow'));await p.waitForTimeout(450);const late=await el.evaluate(e=>+e.style.getPropertyValue('--glow'));check('hover illumination transitions smoothly',early>0&&early<late&&late>.8,{early,late});await p.mouse.move(1400,160);await p.waitForTimeout(700);check('hover dissipates on leave',await el.evaluate(e=>+e.style.getPropertyValue('--glow')<.02));
await p.goBack();await p.waitForFunction(()=>__DXT__.inspect().route==='about',null,{polling:100});check('browser Back works',new URL(p.url()).pathname==='/about');await p.goForward();await p.waitForFunction(()=>__DXT__.inspect().route==='contact',null,{polling:100});check('browser Forward works',new URL(p.url()).pathname==='/contact');
for(const [w,h]of[[390,844],[320,640]]){await p.setViewportSize({width:w,height:h});for(const r of['home','groups','projects','about','contact']){
 await p.goto(BASE+(r==='home'?'/':'/'+r)+'?debug',{waitUntil:'load'});await p.waitForFunction(r=>window.__DXT__?.inspect().route===r,r,{polling:100});check(r+' has no horizontal overflow at '+w,await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 if(r==='home'){await ready(p);check('mobile hero canvas has a real scene at '+w,await p.evaluate(()=>__DXT__.inspect().scene.cars===2&&__DXT__.scene().gl.getError()===0));check('touch page scroll is not trapped',await p.locator('#hero-canvas').evaluate(e=>getComputedStyle(e).touchAction==='pan-y'));await p.screenshot({path:path.join(OUT,'mobile-'+w+'.png'),fullPage:true});}
}await p.locator('.menu-toggle').click();check('mobile menu opens at '+w,await p.locator('.menu-toggle').getAttribute('aria-expanded')==='true');await p.keyboard.press('Escape');check('mobile menu closes with Escape at '+w,await p.locator('.menu-toggle').getAttribute('aria-expanded')==='false');}
const rm=await browser.newPage({viewport:{width:1000,height:750},reducedMotion:'reduce'});await rm.goto(BASE+'/?debug');await ready(rm);await rm.waitForTimeout(1000);const frames=await rm.evaluate(()=>__DXT__.inspect().scene.frames);await rm.waitForTimeout(500);check('reduced-motion renderer sleeps after settling',await rm.evaluate(n=>__DXT__.inspect().scene.frames===n,frames));await rm.close();
const fb=await browser.newPage({viewport:{width:390,height:844}});await fb.addInitScript(()=>{const g=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(t,...a){return /webgl/.test(t)?null:g.call(this,t,...a)}});await fb.goto(BASE+'/?debug');await fb.waitForTimeout(400);check('no-WebGL retains original project art and navigation',await fb.locator('.hero-fallback').isVisible()&&await fb.locator('.hero-actions a').count()===2);await fb.locator('.menu-toggle').click();await fb.locator('header nav a[href="/contact"]').click();check('fallback contacts remain usable',await fb.locator('.contact-row').count()===4);await fb.close();
check('no JavaScript errors in tested routes',errors.length===0,errors);fs.writeFileSync(path.join(OUT,'browser-results.json'),JSON.stringify({browser:browser.version(),backend:'ANGLE SwiftShader',checks,errors},null,2));await browser.close();console.log('TOTAL',checks.length);
})().catch(e=>{console.error(e.stack);fs.writeFileSync(path.join(OUT,'browser-results.json'),JSON.stringify({checks,errors,error:e.stack},null,2));process.exit(1)});
