const {chromium}=require('playwright'),fs=require('fs');(async()=>{
const b=await chromium.launch({headless:true,args:['--no-sandbox','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']}),p=await b.newPage({viewport:{width:1280,height:800}});let errors=[];p.on('pageerror',e=>errors.push(e.message));await p.addInitScript(()=>localStorage.setItem('dxt-settings',JSON.stringify({quality:'low',paused:true})));await p.goto((process.env.DXT_BASE_URL||'http://127.0.0.1:3000')+'/?debug');await p.waitForFunction(()=>__DXT__.scene()?.frames>0&&__DXT__.cards()?.ready,null,{polling:100});
let results=[];function ck(name,ok,detail){results.push({name,pass:!!ok,detail});console.log(name,ok,detail??'');if(!ok)throw Error(name);}
await p.mouse.move(810,165);const yaw=await p.evaluate(()=>__DXT__.scene().yaw);await p.mouse.down();await p.mouse.move(925,172,{steps:6});await p.mouse.up();await p.waitForTimeout(200);ck('Drag rotates true scene camera',await p.evaluate(y=>Math.abs(__DXT__.scene().yaw-y)>.05,yaw));
await p.locator('#reset-view').click();await p.waitForFunction(()=>Math.abs(__DXT__.scene().yaw+.72)<.02,null,{polling:100,timeout:20000});ck('Reset settles to reference angle',true);
await p.locator('#expand-view').click();await p.waitForTimeout(300);ck('Expanded scene fills viewport',await p.locator('.hero').evaluate(e=>e.classList.contains('is-expanded')&&Math.abs(e.getBoundingClientRect().height-innerHeight)<2));
await p.keyboard.press('Escape');await p.waitForTimeout(300);ck('Escape restores panoramic hero',await p.locator('.hero').evaluate(e=>!e.classList.contains('is-expanded')&&e.getBoundingClientRect().height<innerHeight*.5));
await p.locator('#quality').click();ck('Quality control retains real renderer',await p.evaluate(()=>__DXT__.scene().renderer.getContext().getError()===0));
const cdp=await p.context().newCDPSession(p);await p.setViewportSize({width:390,height:844});await p.locator('.games-band').scrollIntoViewIfNeeded();await p.waitForTimeout(500);const gallery=p.locator('.perspective-gallery').first();const r=await gallery.boundingBox();await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:r.x+220,y:r.y+r.height*.55}]});for(const x of[190,150,110,70])await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:r.x+x,y:r.y+r.height*.55}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await p.waitForTimeout(400);ck('Touch scroll stays on the home route',await p.evaluate(()=>location.pathname==='/'));ck('Touch actually moves the gallery',await gallery.evaluate(e=>e.scrollLeft>15));
const glerr=await p.evaluate(()=>__DXT__.cards().gl.getError());ck('No GL errors after resize, expand and touch',glerr===0,glerr);ck('No JavaScript errors',errors.length===0,errors);fs.writeFileSync(require('path').resolve('previews/interaction-r3.json'),JSON.stringify({results,errors},null,2));await b.close();
})().catch(e=>{console.error(e.stack);process.exit(1)});
