import{THREE,V,physical,luminous,box,ring,cylinder,label,glow,seedRandom,canvasTexture,simpleVertex,noiseGLSL}from'./shared.js';
import{RoomEnvironment,mergeGeometries}from'../../vendor/deps.js';
/** Procedural architecture. No concept-art backdrop is present in this scene. */
export class Environment{
 constructor(scene,renderer){this.group=new THREE.Group();this.group.name='Architecture';scene.add(this.group);const group=this.group;
  scene.background=new THREE.Color(0x040a1c);scene.fog=new THREE.FogExp2(0x07152d,.025);
  const pmrem=new THREE.PMREMGenerator(renderer);this.env=pmrem.fromScene(new RoomEnvironment(),.03);scene.environment=this.env.texture;scene.environmentIntensity=.28;pmrem.dispose();
  this.dark=physical(0x060c19,.38,.86);this.mid=physical(0x263954,.43,.62);this.light=luminous(0x548cff,3.5);this.dim=luminous(0x264b99,.5);
  const metalRng=seedRandom(807);const metal=canvasTexture((ctx,w,h)=>{const im=ctx.createImageData(w,h);for(let y=0;y<h;y++)for(let x=0;x<w;x++){const i=(y*w+x)*4;const v=94+Math.floor(metalRng()*36)+Math.sin(x*.08)*8;im.data[i]=v;im.data[i+1]=v+7;im.data[i+2]=v+14;im.data[i+3]=255;}ctx.putImageData(im,0,0);ctx.strokeStyle='#738097';ctx.globalAlpha=.22;ctx.lineWidth=.5;for(let i=0;i<160;i++){const x=metalRng()*w,y=metalRng()*h;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x+metalRng()*12,y+metalRng()*200);ctx.stroke();}},256,512);metal.wrapS=metal.wrapT=THREE.RepeatWrapping;metal.repeat.set(.6,.32);[this.mid,this.dark].forEach(m=>{m.map=metal;m.bumpMap=metal;m.bumpScale=.015;m.roughnessMap=metal;});
  const hemi=new THREE.HemisphereLight(0x779bff,0x080d19,.60);scene.add(hemi);
  const key=new THREE.SpotLight(0xb0cdff,140,45,.83,.85,1.6);key.position.set(-4,9,7);key.target.position.set(0,1,0);scene.add(key,key.target);
  const leftFace=new THREE.PointLight(0x497bc8,90,17,2);leftFace.position.set(-9,6,3);scene.add(leftFace);const rightFace=new THREE.PointLight(0x4a78db,90,17,2);rightFace.position.set(9,7,2);scene.add(rightFace);
  const key2=new THREE.DirectionalLight(0x4a77ff,1.1);key2.position.set(6,5,-4);scene.add(key2);
  [[0,2.0,1.5,18,0x396dff],[5,3,1,34,0x3a69ff],[-5,3,1,34,0x457aff],[0,8,-5,90,0x92b4ff]].forEach(([x,y,z,p,c])=>{const l=new THREE.PointLight(c,p,18,2);l.position.set(x,y,z);scene.add(l);});
  this.pedestal=new THREE.Group();this.pedestal.scale.set(1.45,1,1.45);group.add(this.pedestal);
  this.ringMaterial=new THREE.ShaderMaterial({vertexShader:simpleVertex,fragmentShader:`varying vec3 vWorld;void main(){float a=atan(vWorld.z,vWorld.x);float r=length(vWorld.xz);float hotspot=pow(max(0.,sin(a*3.+r*.6)),24.);float front=1.-smoothstep(1.,4.,vWorld.z);float outer=smoothstep(4.,5.5,r);float base=mix(.58,.055,outer);float brightness=(base+hotspot*2.1)*mix(mix(.72,.22,outer),1.,front);gl_FragColor=vec4(vec3(.25,.58,2.3)*brightness,1.);}`});
  cylinder(this.pedestal,4.25,.025,.008,this.dark);cylinder(this.pedestal,3.8,.025,.024,this.mid);cylinder(this.pedestal,2.64,.30,.24,this.dark);cylinder(this.pedestal,2.55,.065,.425,this.mid);cylinder(this.pedestal,2.36,.02,.47,this.dark);
  [[4.22,.014,.03],[3.75,.018,.045],[3.54,.010,.045],[2.59,.026,.405],[2.47,.012,.465],[2.08,.018,.49],[1.72,.022,.488],[1.31,.012,.49],[.70,.015,.51]].forEach(([r,t,y])=>ring(this.pedestal,r,t,y,this.ringMaterial));
  [[3.9,.014,.02],[3.6,.012,.035],[2.26,.035,.48],[1.83,.04,.48]].forEach(([r,t,y])=>ring(this.pedestal,r,t,y,this.dark));
  const bolts=[];for(let i=0;i<72;i++){const a=i/72*Math.PI*2;const b=new THREE.BoxGeometry(.024,.025,.26);b.rotateY(a);b.translate(Math.sin(a)*3.57,.05,Math.cos(a)*3.57);bolts.push(b);}const bolted=new THREE.Mesh(mergeGeometries(bolts),this.mid);this.pedestal.add(bolted);
  const segments=[];for(let i=0;i<32;i++){const a=i/32*Math.PI*2;const b=new THREE.BoxGeometry(.1,.05,.016);b.rotateY(a);b.translate(Math.sin(a)*2.647,.23,Math.cos(a)*2.647);segments.push(b);}this.pedestal.add(new THREE.Mesh(mergeGeometries(segments),this.dim));
  this.pedestalGlow=new THREE.Mesh(new THREE.PlaneGeometry(8,8),new THREE.ShaderMaterial({vertexShader:simpleVertex,fragmentShader:`uniform float uTime;varying vec2 vUv;${noiseGLSL}void main(){vec2 p=vUv-.5;float r=length(p);float a=atan(p.y,p.x);float center=exp(-r*r*200.);float rings=pow(max(0.,sin(r*128.-uTime*1.2)),35.)*exp(-r*15.);float dust=fbm(p*12.+uTime*.02)*exp(-r*13.);float rays=pow(max(0.,sin(a*24.+r*14.)),18.)*.03*exp(-r*8.);gl_FragColor=vec4(vec3(.10,.34,1.5)*(center*3.+rings*.30+dust*.09+rays),.8);}`,uniforms:{uTime:{value:0}},transparent:true,blending:THREE.AdditiveBlending,depthWrite:false,side:THREE.DoubleSide}));this.pedestalGlow.rotation.x=-Math.PI/2;this.pedestalGlow.position.y=.515;this.pedestalGlow.scale.set(1.4,1.4,1);group.add(this.pedestalGlow);
  const rnd=seedRandom(902);const wallMat=physical(0x060e1c,.6,.6);wallMat.side=THREE.BackSide;const wall=new THREE.Mesh(new THREE.CylinderGeometry(13,13,12,72,1,true,Math.PI/2,Math.PI),wallMat);wall.position.set(0,4.5,-.3);group.add(wall);
  const geometries=[];for(let i=0;i<34;i++){const a=Math.PI/2+i/33*Math.PI,r=9.2+rnd()*2;const h=2.2+rnd()*8.3,w=.36+rnd()*.75;const b=new THREE.BoxGeometry(w,h,.65+rnd()*.7);b.rotateY(a);b.translate(Math.sin(a)*r,h/2,Math.cos(a)*r-4.0);geometries.push(b);}group.add(new THREE.Mesh(mergeGeometries(geometries),this.dark));
  // Larger silhouette monoliths establish the same architectural framing as the concept.
  this.monolith(-9.4,12.0,-6.8,1.8,-.075,['CREATE','BUILD','LEARN','IMPROVE','REPEAT']);
  this.monolith(9.4,12.3,-6.8,1.8,.09,['MORE','THAN','GAMES']);
  this.monolith(-11.7,11.0,.5,1.65,.20,[]);this.monolith(11.7,10.8,.4,1.80,-.10,[]);
  for(const y of [12.3,13.5,14.8]){for(const [radius,thickness,material] of [[13,.08,this.dark],[12.92,.012,y===12.3?this.light:this.dim],[13.35,.035,this.mid]]){const arc=new THREE.Mesh(new THREE.TorusGeometry(radius,thickness,8,160,Math.PI),material);arc.rotation.x=-Math.PI/2;arc.position.y=y;group.add(arc);}}
  for(let i=0;i<16;i++){const a=Math.PI/2+i/15*Math.PI;const r=9.0,x=Math.sin(a)*r,z=Math.cos(a)*r;
   box(group,[.014,1.6,.02],[x,3.4+rnd()*2,z],i%3===0?this.light:this.dim);
   if(i%3===0)glow(group,[x,.3,z],.6,1.4);
  }
  const rockMats=[physical(0x080e19,.64,.50),physical(0x070c15,.51,.55)];
  const rockGeo=new THREE.IcosahedronGeometry(1,1);const rocks=new THREE.InstancedMesh(rockGeo,rockMats[0],45);const dummy=new THREE.Object3D();for(let i=0;i<45;i++){const side=i%2?1:-1;dummy.position.set(side*(4.7+rnd()*9),rnd()*.15-.18,-6-rnd()*9);dummy.rotation.set(rnd()*3,rnd()*3,rnd()*3);const s=.17+rnd()*.62;dummy.scale.set(s,s*(.65+rnd()),s*(.5+rnd()));dummy.updateMatrix();rocks.setMatrixAt(i,dummy.matrix);}group.add(rocks);
  this.floating=[];for(let i=0;i<6;i++){const rock=new THREE.Mesh(new THREE.IcosahedronGeometry(.33+rnd()*.25,0),rockMats[1]);rock.position.set((i%2?1:-1)*(5+rnd()*4),2+rnd()*5,-5-rnd()*6);rock.rotation.set(rnd()*3,rnd()*3,0);rock.userData.y=rock.position.y;rock.userData.phase=rnd()*6;this.floating.push(rock);group.add(rock);}
  this.beams=[];for(let i=0;i<7;i++){const beam=new THREE.Mesh(new THREE.PlaneGeometry(1.25+i%2*.9,12),new THREE.ShaderMaterial({vertexShader:simpleVertex,fragmentShader:`precision highp float;uniform float uTime,uSeed;varying vec2 vUv;${noiseGLSL}void main(){float x=abs(vUv.x-.5)*2.;float edge=pow(max(0.,1.-x),2.5);float y=smoothstep(0.,.3,vUv.y)*(1.-smoothstep(.78,1.,vUv.y));float bands=.4+.6*noise(vec2(vUv.x*15.+uSeed,vUv.y*2.+uTime*.08));gl_FragColor=vec4(vec3(.20,.43,1.),edge*y*bands*.15);}`,uniforms:{uTime:{value:0},uSeed:{value:i*13.}},transparent:true,blending:THREE.AdditiveBlending,depthWrite:false,side:THREE.DoubleSide}));beam.position.set(-5.5+i*1.8,5.9,-3.4-(i%3));beam.rotation.z=(i-3)*-.035;group.add(beam);this.beams.push(beam);}
  const pts=[];for(let i=0;i<430;i++){pts.push((rnd()-.5)*25,.2+rnd()*11,(rnd()-.7)*22);}const pg=new THREE.BufferGeometry();pg.setAttribute('position',new THREE.Float32BufferAttribute(pts,3));this.particles=new THREE.Points(pg,new THREE.PointsMaterial({color:0x739bff,size:.014,transparent:true,opacity:.24,depthWrite:false,blending:THREE.AdditiveBlending,sizeAttenuation:true}));group.add(this.particles);
  const mist=new THREE.Mesh(new THREE.PlaneGeometry(27,4),new THREE.ShaderMaterial({vertexShader:simpleVertex,fragmentShader:`uniform float uTime;varying vec2 vUv;${noiseGLSL}void main(){float n=fbm(vUv*vec2(8.,3.)+vec2(uTime*.025,0.));float a=exp(-pow((vUv.y-.42)*5.,2.))*smoothstep(0.,.12,vUv.x)*(1.-smoothstep(.88,1.,vUv.x));gl_FragColor=vec4(.10,.23,.55,n*a*.12);}`,uniforms:{uTime:{value:0}},transparent:true,blending:THREE.AdditiveBlending,depthWrite:false}));mist.position.set(0,.9,-5);group.add(mist);this.mist=mist;for(const point of [[-5.4,.19,.4],[5.35,.2,.8],[-3.65,.5,-.6],[3.4,.5,-1.2]])glow(group,point,.65,2.3,0x75aaff);
 }
 monolith(x,h,z,w,rotation,words){const g=new THREE.Group();g.position.set(x,h/2-.1,z);g.rotation.z=rotation;g.rotation.y=x>0?-.12:.12;this.group.add(g);const shape=new THREE.Shape();shape.moveTo(-w/2,-h/2);shape.lineTo(w/2,-h/2);shape.lineTo(w/2,h/2-.35);shape.lineTo(-w/2+.15,h/2);shape.closePath();const slab=new THREE.Mesh(new THREE.ExtrudeGeometry(shape,{depth:.65,bevelEnabled:true,bevelSize:.03,bevelThickness:.03,bevelSegments:1,steps:1}),this.mid);g.add(slab);box(g,[.015,h*.89,.03],[-w/2-.008,0,.69],this.dim);if(words.length){const l=label(g,words,[0,h*.20,.70],w*.82,w*1.20,'#648cdb',56);l.userData.label=true;}return g;}
 update(time,reduced){this.pedestalGlow.material.uniforms.uTime.value=time;this.mist.material.uniforms.uTime.value=time;this.beams.forEach(b=>b.material.uniforms.uTime.value=time);if(!reduced){this.particles.rotation.y=time*.004;this.floating.forEach(r=>{r.position.y=r.userData.y+Math.sin(time*.42+r.userData.phase)*.10;r.rotation.y+=.0004;});}}
}
