import{THREE,physical,luminous,glow}from'./shared.js';
/** Extruded hollow square with a real square aperture, beveled edges and orbit curves. */
export class Hub{
 constructor(scene){this.group=new THREE.Group();this.group.name='Roblox core';this.group.position.set(0,2.65,0);this.group.scale.setScalar(1.35);scene.add(this.group);this.rotor=new THREE.Group();this.group.add(this.rotor);
  const size=1.83,half=size/2,hole=.30;const shape=new THREE.Shape();shape.moveTo(-half,-half);shape.lineTo(half,-half);shape.lineTo(half,half);shape.lineTo(-half,half);shape.closePath();const cut=new THREE.Path();cut.moveTo(-hole,-hole);cut.lineTo(-hole,hole);cut.lineTo(hole,hole);cut.lineTo(hole,-hole);cut.closePath();shape.holes.push(cut);
  const geo=new THREE.ExtrudeGeometry(shape,{depth:.32,bevelEnabled:true,bevelSegments:3,steps:1,bevelSize:.024,bevelThickness:.024,curveSegments:1});geo.translate(0,0,-.16);
  this.uniforms={uTime:{value:0},uHover:{value:0},uPoint:{value:new THREE.Vector3()}};
  const material=new THREE.MeshPhysicalMaterial({transparent:true,color:0x285ad7,metalness:.13,roughness:.27,clearcoat:1,clearcoatRoughness:.17,emissive:0x09265e,emissiveIntensity:.50,envMapIntensity:.65,ior:1.47});
  material.onBeforeCompile=s=>{Object.assign(s.uniforms,this.uniforms);s.vertexShader=s.vertexShader.replace('#include <common>','#include <common>\nuniform float uTime,uHover;uniform vec3 uPoint;varying vec3 vLogoLocal;').replace('#include <begin_vertex>','#include <begin_vertex>\nvLogoLocal=position;float d=length(position.xy-uPoint.xy);transformed.z+=sin(d*12.-uTime*7.)*exp(-d*1.8)*uHover*.04;');s.fragmentShader=s.fragmentShader.replace('#include <common>','#include <common>\nvarying vec3 vLogoLocal;uniform float uTime;').replace('#include <opaque_fragment>',`float vapor=sin(vLogoLocal.x*5.+sin(vLogoLocal.y*3.-uTime*.15))*sin(vLogoLocal.y*4.+uTime*.15)*.5+.5;vec3 energy=vec3(.016,.045,.24)*(.72+vapor*.35);outgoingLight+=energy;\n#include <opaque_fragment>`);};
  this.mesh=new THREE.Mesh(geo,material);this.rotor.add(this.mesh);this.rotor.rotation.set(.10,-.30,-.26);
  for(const h of [half,hole]){const vertices=[[-h,-h,.16],[h,-h,.16],[h,h,.16],[-h,h,.16]].map(p=>new THREE.Vector3(...p));const line=new THREE.LineLoop(new THREE.BufferGeometry().setFromPoints(vertices),new THREE.LineBasicMaterial({color:new THREE.Color(0x92c5ff).multiplyScalar(1.4),transparent:true,opacity:.75}));this.rotor.add(line);}

  this.orbits=[];for(let i=0;i<3;i++){const pts=[];for(let j=0;j<=180;j++){const a=j/180*Math.PI*2;pts.push(new THREE.Vector3(Math.cos(a)*1.64,Math.sin(a)*.79,0));}const curve=new THREE.CatmullRomCurve3(pts,true);const orbit=new THREE.Mesh(new THREE.TubeGeometry(curve,180,.009,5,true),new THREE.ShaderMaterial({vertexShader:`varying vec2 vUv;void main(){vUv=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}`,fragmentShader:`uniform float uTime,uPhase,uVisibility;varying vec2 vUv;void main(){float d=fract(vUv.x-uTime*.04+uPhase);float flare=pow(1.-d,16.);gl_FragColor=vec4(vec3(.22,.63,2.5)*( .28+flare*3.),(.43+flare*.5)*uVisibility);}`,uniforms:{uTime:{value:0},uPhase:{value:i/3},uVisibility:{value:1}},transparent:true,blending:THREE.AdditiveBlending,depthWrite:false}));orbit.rotation.set(i*.56,.25+i*.65,-.48+i*.54);this.group.add(orbit);this.orbits.push(orbit);}
  this.sparks=[glow(this.group,[-1.5,-.1,.4],.42,2.4),glow(this.group,[1.40,.45,.3],.32,2.0)];
  this.baseHalo=glow(scene,[0,.63,0],2.1,2.5);this.hover=0;
 }
 update(time,motion,reduced){this.uniforms.uTime.value=time;this.uniforms.uHover.value=this.hover;this.group.position.y=(this.baseY??2.65)+(reduced?0:Math.sin(time*.65)*.055);this.rotor.rotation.set(.13+(reduced?0:Math.sin(time*.31)*.035),-.27+(reduced?0:Math.sin(time*.27)*.075),-.26-motion.rotation);const visibility=1-THREE.MathUtils.smoothstep(motion.focusAmount,.08,.78);this.group.visible=visibility>.001;this.mesh.material.opacity=visibility;this.mesh.material.depthWrite=visibility>.98;this.rotor.children.forEach(child=>{if(child.isLineLoop)child.material.opacity=.75*visibility;});this.orbits.forEach(o=>{o.material.uniforms.uTime.value=time;o.material.uniforms.uVisibility.value=visibility;});this.sparks.forEach(s=>s.material.opacity=visibility);this.baseHalo.material.opacity=visibility;}
}
