import { THREE } from '../../vendor/deps.js';
export {THREE};
export const V=THREE.Vector3;
export function physical(color=0x111d37,roughness=.3,metalness=.78){return new THREE.MeshStandardMaterial({color,roughness,metalness});}
export function luminous(color=0x477aff,intensity=3){return new THREE.MeshBasicMaterial({color:new THREE.Color(color).multiplyScalar(intensity),toneMapped:false});}
export function box(group,size,position,material,rotation=[0,0,0]){const m=new THREE.Mesh(new THREE.BoxGeometry(...size),material);m.position.set(...position);m.rotation.set(...rotation);group.add(m);return m;}
export function ring(group,radius,tube,y,material){const m=new THREE.Mesh(new THREE.TorusGeometry(radius,tube,8,144),material);m.rotation.x=Math.PI/2;m.position.y=y;group.add(m);return m;}
export function cylinder(group,radius,height,y,material){const m=new THREE.Mesh(new THREE.CylinderGeometry(radius,radius,height,96),material);m.position.y=y;m.receiveShadow=true;group.add(m);return m;}
export function seedRandom(seed=27){return ()=>{seed|=0;seed=seed+0x6D2B79F5|0;let t=Math.imul(seed^seed>>>15,1|seed);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296;};}
export function canvasTexture(draw,width=512,height=512){const c=document.createElement('canvas');c.width=width;c.height=height;draw(c.getContext('2d'),width,height);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;t.anisotropy=4;return t;}
export function label(group,lines,position,width,height,color='#648ee8',fontSize=44){const tex=canvasTexture((ctx,w,h)=>{ctx.fillStyle=color;ctx.textAlign='center';ctx.font=`500 ${fontSize}px Arial`;lines.forEach((s,i)=>ctx.fillText(s,w/2,64+i*fontSize*1.52));},512,512);const mat=new THREE.MeshBasicMaterial({map:tex,transparent:true,depthWrite:false,side:THREE.DoubleSide,toneMapped:false});const m=new THREE.Mesh(new THREE.PlaneGeometry(width,height),mat);m.position.set(...position);group.add(m);return m;}
let glowMap;
export function glow(group,position,scale=1,intensity=1,color=0x376eff){if(!glowMap)glowMap=canvasTexture((ctx,w,h)=>{const g=ctx.createRadialGradient(w/2,h/2,0,w/2,h/2,w/2);g.addColorStop(0,'rgba(255,255,255,1)');g.addColorStop(.055,'rgba(220,240,255,.85)');g.addColorStop(.16,'rgba(125,180,255,.25)');g.addColorStop(.42,'rgba(60,100,255,.055)');g.addColorStop(1,'rgba(30,70,255,0)');ctx.fillStyle=g;ctx.fillRect(0,0,w,h);},128,128);const s=new THREE.Sprite(new THREE.SpriteMaterial({map:glowMap,color:new THREE.Color(color).multiplyScalar(intensity),transparent:true,blending:THREE.AdditiveBlending,depthWrite:false,toneMapped:false}));s.position.set(...position);s.scale.setScalar(scale);group.add(s);return s;}
export const simpleVertex=`varying vec2 vUv;varying vec3 vWorld;void main(){vUv=uv;vec4 w=modelMatrix*vec4(position,1.);vWorld=w.xyz;gl_Position=projectionMatrix*viewMatrix*w;}`;
export const noiseGLSL=`float hash21(vec2 p){p=fract(p*vec2(123.34,456.21));p+=dot(p,p+45.32);return fract(p.x*p.y);}float noise(vec2 p){vec2 i=floor(p),f=fract(p);f=f*f*(3.-2.*f);return mix(mix(hash21(i),hash21(i+vec2(1,0)),f.x),mix(hash21(i+vec2(0,1)),hash21(i+vec2(1,1)),f.x),f.y);}float fbm(vec2 p){float v=0.,a=.5;for(int i=0;i<4;i++){v+=noise(p)*a;p=p*2.03+13.7;a*=.5;}return v;}`;
