import {CONTENT as C} from '../content.js';import {icon,logo,ext} from '../ui/icons.js';
export const socialItems=[['discord','Discord','Berserk community'],['instagram','Instagram','@matheus.dxt'],['youtube','YouTube','@xaudriy'],['roblox','Roblox','DXT’s profile']];
export function socials(cls=''){return `<div class="social-grid ${cls}">${socialItems.map(([key,title,sub])=>ext(C.links[key],`<span class="social-icon ${key}">${icon(key)}</span><span><strong>${title}</strong><small>${sub}</small></span>${icon('external','social-arrow')}`,'social material')).join('')}</div>`;}
export function groupCard(g,large=false){return `<article class="group-card material ${g.tone} ${large?'large':''}"><a class="group-art ${g.key}" href="${C.links[g.key]}" target="_blank" rel="noopener noreferrer" aria-label="Open ${g.name} on Roblox"><div class="art-grid"></div>${logo(g.key)}<span class="corner-icon">${icon('external')}</span></a><div class="group-copy"><h3>${g.name}</h3><p>${g.text}</p>${large?`<div class="group-games" data-group="${g.id}">${g.key==='revline'?ext(C.links.game,`${icon('wheel')}<span>BERSERK DRIFT X<small>Main project · In development</small></span>${icon('external')}`,'game-row'):''}</div>`:''}<div class="group-foot"><span class="micro">ROBLOX COMMUNITY</span>${ext(C.links[g.key],`View group ${icon('arrow')}`,'tiny-link')}</div></div></article>`;}
export function projectRows(){return C.upcoming.map((p,i)=>`<a class="project-row material" href="/projects" data-route><span class="project-thumb thumb-${i}">${icon(p.icon)}</span><span><strong>${p.name}</strong><small>${p.type}</small></span><span class="circle-arrow">${icon('arrow')}</span></a>`).join('');}
const localCard=(href,content,cls='')=>`<a href="${href}" data-route class="skew-card material ${cls}"><div class="skew-card-content">${content}</div></a>`;
export function home(){return `<div class="home-page">
<section class="hero" aria-label="Berserk Drift X interactive 3D showcase">
 <div class="hero-art"><img class="hero-fallback" src="/assets/images/race.webp" alt="Original Berserk Drift X artwork"><canvas id="hero-canvas" tabindex="0" aria-label="3D drift cars. Drag horizontally to orbit. Arrow keys change view; Home resets it."></canvas></div>
 <div class="hero-shade"></div><div class="hero-copy"><h1 class="sr-only">Berserk Drift X</h1>${logo('berserk','hero-logo')}<p class="hero-tagline">A DRIFTING EXPERIENCE ON ROBLOX.<br><em>THE MAIN PROJECT. STILL IN THE MAKING.</em></p><div class="hero-actions">${ext(C.links.game,`${icon('roblox')} Play now`,'button primary material')}<a href="/groups" data-route class="button outline material">Learn more ${icon('arrow')}</a></div></div>
 <div class="hero-mantra" aria-hidden="true">DRIFT.<br>BUILD.<br>CONNECT.<span></span></div>
 <div class="scene-tools"><button id="expand-view" class="scene-tool material" aria-pressed="false">${icon('wheel')}<span>Explore in 3D</span></button><button id="reset-view" class="scene-tool reset material" aria-label="Reset car camera">↺</button></div>
 <div class="hero-corner left-corner"></div><div class="hero-corner right-corner"></div>
</section>
<section class="ribbon ribbon-groups" aria-labelledby="groups-title">
 <div class="ribbon-fill"></div><div class="orange-slice"></div><div class="ribbon-inner">
 <div class="ribbon-heading"><span class="micro ribbon-index">01 / ON ROBLOX</span><h2 id="groups-title">ROBLOX GROUPS & GAMES</h2><i class="heading-stroke"></i><p>THE COMMUNITIES.<br>THE GAMES. THE NEXT CHAPTER.</p><a href="/groups" data-route class="button mini outline material">${icon('roblox')}Explore on Roblox ${icon('arrow')}</a></div>
 <div class="ribbon-cards">${ext(C.links.game,`<div class="skew-card-content"><img class="card-photo" src="/assets/images/race.webp" alt="Berserk Drift X"><div class="card-vignette"></div>${logo('berserk','card-mark')}<div class="card-caption"><strong>Berserk Drift X</strong><span>MAIN PROJECT / IN DEVELOPMENT</span></div>${icon('external','card-arrow')}</div>`,'skew-card material main-game')}${C.groups.map(g=>ext(C.links[g.key],`<div class="skew-card-content"><div class="group-card-image ${g.key}">${logo(g.key)}</div><div class="card-caption"><strong>${g.name}</strong><span>ROBLOX COMMUNITY</span></div>${icon('external','card-arrow')}</div>`,'skew-card material '+g.tone)).join('')}</div>
 <p class="ribbon-aside">PLAY.<br>BUILD.<br>TOGETHER.</p>
 </div>
</section>
<section class="ribbon ribbon-projects" aria-labelledby="projects-title"><div class="ribbon-fill"></div><div class="ribbon-inner">
 <div class="ribbon-heading"><span class="micro ribbon-index">02 / IN THE WORKS</span><h2 id="projects-title">OTHER PROJECTS</h2><i class="heading-stroke"></i><p>DIFFERENT IDEAS.<br>THE SAME CURIOSITY.</p><a href="/projects" data-route class="button mini outline material">Explore projects ${icon('arrow')}</a></div>
 <div class="ribbon-cards">${C.upcoming.map((p,i)=>localCard('/projects',`<div class="future-art future-art-${i}">${i===0?'<img src="/assets/images/race.webp" alt="" loading="lazy">':logo('dxt')}<div class="future-wire">${icon(p.icon)}</div></div><div class="card-caption"><strong>${p.name}</strong><span>COMING SOON / ${p.type}</span></div>${icon('external','card-arrow')}`,'future-teaser')).join('')}</div><p class="ribbon-aside">NEW IDEAS.<br>BEYOND<br>THE ROAD.</p>
 </div></section>
<section class="bio-ribbon" aria-labelledby="bio-title"><div class="bio-color"></div><div class="bio-person"><img data-avatar src="/assets/images/avatar.webp" alt="DXT’s Roblox avatar" class="live-avatar"></div><div class="bio-title"><span>WHO IS</span><h2 id="bio-title">DXT?</h2></div><div class="bio-brief"><p>THE CREATOR BEHIND BERSERK DRIFT X.<br>GAMES, CAR CULTURE AND IDEAS IN THE MAKING.<br>ON ROBLOX AND BEYOND.</p><a href="/about" data-route class="button mini outline material">Read my story ${icon('arrow')}</a></div><div class="bio-motto" aria-hidden="true">SAME<br>PASSION.<br>DIFFERENT<br>WORLDS.</div><div class="bio-flag">${logo('dxt')}</div></section>
<section class="social-strip"><div class="social-heading"><h2>SOCIALS & CONTACT</h2><i class="heading-stroke"></i><p class="micro">LET’S CONNECT.<br>GAMES, IDEAS, OR JUST A CONVERSATION.</p></div>${socials()}<div class="social-signoff">${logo('dxt')}<span class="micro">THANK YOU<br>FOR BEING HERE.</span></div></section>
</div>`;}
const intro=(n,kicker,title,text)=>`<div class="page-intro"><p class="eyebrow"><i></i>${n} / ${kicker}</p><h1 tabindex="-1">${title}</h1><p>${text}</p></div>`;
export function groups(){return `<section class="inner-page groups-page">${intro('02','ROBLOX','Games. Groups.<br><em>Good company.</em>','Two spaces for the things I build on Roblox. Explore the communities and their games.')}<div class="group-showcase">${C.groups.map(g=>groupCard(g,true)).join('')}</div><div class="page-note">${icon('game')}<span>More experiences will appear here as they become public.</span>${ext(C.links.roblox,'My Roblox profile '+icon('external'),'tiny-link')}</div></section>`;}
export function projects(){return `<section class="inner-page projects-page">${intro('03','BEYOND THE MAIN PROJECT','More than<br><em>one idea.</em>','A place for the next games, addons and systems. On Roblox and beyond.')}<div class="future-grid">${C.upcoming.map((p,i)=>`<article class="future-card material"><span class="future-number">0${i+1}</span><div class="future-object object-${i}">${icon(p.icon)}</div><span class="pill">COMING SOON</span><h2>${p.name}</h2><p>${p.description}</p><span class="micro">${p.type}</span></article>`).join('')}</div><div class="page-note">${icon('spark')}<span>Nothing announced yet. Follow along for what comes next.</span>${ext(C.links.youtube,'Follow on YouTube '+icon('external'),'tiny-link')}</div></section>`;}
export function about(){return `<section class="inner-page about-page"><div class="about-grid"><div>${intro('04','THE PERSON BEHIND IT','Who is<br><em>DXT?!</em>','A creator with cars on the mind and projects in the making.')}<div class="biography"><p>I’m DXT, the developer behind <strong>Berserk Drift X</strong>. This is my personal space for the things I create, the communities around them and the ideas I’m exploring.</p><p>My main project lives on Roblox. What comes next can go beyond it: games, addons, systems and new experiments.</p><div class="bio-tags"><span>${icon('wheel')}Car culture</span><span>${icon('game')}Game development</span><span>${icon('code')}New ideas</span></div>${ext(C.links.roblox,`Meet me on Roblox ${icon('external')}`,'button outline material')}</div></div><div class="identity-stage"><div class="logo-model" id="logo-model"><img src="/assets/icons/dxt.webp" alt="DXT logo"><canvas id="logo-canvas" aria-label="Interactive 3D DXT logo" tabindex="0"></canvas><span class="micro model-hint">DXT / ORIGINAL 3D MARK</span></div><a class="profile-card material" href="${C.links.roblox}" target="_blank" rel="noopener noreferrer"><img data-avatar class="profile-avatar" src="/assets/images/avatar.webp" alt="DXT Roblox avatar"><span><small>ROBLOX PROFILE</small><strong data-profile-name>DXT</strong><span class="micro" data-profile-handle>VIEW MY PROFILE</span></span>${icon('external')}</a></div></div></section>`;}
export function contact(){return `<section class="inner-page contact-page">${intro('05','SOCIALS & CONTACT','Let’s<br><em>connect.</em>','A project, an idea, or just a conversation. Find me here.')}<div class="contact-layout"><div class="contact-links">${socialItems.map(([key,title,sub],i)=>ext(C.links[key],`<span class="contact-number">0${i+1}</span>${icon(key)}<span><strong>${title}</strong><small>${sub}</small></span>${icon('external')}`,'contact-row material')).join('')}</div><aside class="contact-brand"><img src="/assets/icons/dxt.webp" alt="DXT"><p>THE NEXT CHAPTER<br>STARTS WITH<br><em>A CONVERSATION.</em><span class="micro">PERSONAL SPACE / DXT</span></p></aside></div></section>`;}
export function notFound(){return `<section class="inner-page">${intro('404','WRONG TURN','Off the<br><em>track.</em>','This page does not exist. Let’s get you back to the main project.')}<a href="/" data-route class="button primary material">Back to Berserk ${icon('arrow')}</a></section>`;}
export const pages={home,groups,projects,about,contact,'not-found':notFound};
