import {home} from './home-reference.js';export {home};
import {CONTENT as C} from '../content.js';import {icon,logo,ext} from '../ui/icons.js';
export const socialItems=[['discord','Discord','Berserk community'],['instagram','Instagram','@matheus.dxt'],['youtube','YouTube','@xaudriy'],['roblox','Roblox','DXT’s profile']];
export function socials(cls=''){return `<div class="social-grid ${cls}">${socialItems.map(([key,title,sub])=>ext(C.links[key],`<span class="social-icon ${key}">${icon(key)}</span><span><strong>${title}</strong><small>${sub}</small></span>${icon('external','social-arrow')}`,'social material')).join('')}</div>`;}
export function groupCard(g,large=false){return `<article class="group-card material ${g.tone} ${large?'large':''}"><a class="group-art ${g.key}" href="${C.links[g.key]}" target="_blank" rel="noopener noreferrer" aria-label="Open ${g.name} on Roblox"><div class="art-grid"></div>${logo(g.key)}<span class="corner-icon">${icon('external')}</span></a><div class="group-copy"><h3>${g.name}</h3><p>${g.text}</p>${large?`<div class="group-games" data-group="${g.id}">${g.key==='revline'?ext(C.links.game,`${icon('wheel')}<span>BERSERK DRIFT X<small>Main project · In development</small></span>${icon('external')}`,'game-row'):''}</div>`:''}<div class="group-foot"><span class="micro">ROBLOX COMMUNITY</span>${ext(C.links[g.key],`View group ${icon('arrow')}`,'tiny-link')}</div></div></article>`;}
export function projectRows(){return C.upcoming.map((p,i)=>`<a class="project-row material" href="/projects" data-route><span class="project-thumb thumb-${i}">${icon(p.icon)}</span><span><strong>${p.name}</strong><small>${p.type}</small></span><span class="circle-arrow">${icon('arrow')}</span></a>`).join('');}
const localCard=(href,content,cls='')=>`<a href="${href}" data-route class="skew-card material ${cls}"><div class="skew-card-content">${content}</div></a>`;
const intro=(n,kicker,title,text)=>`<div class="page-intro"><p class="eyebrow"><i></i>${n} / ${kicker}</p><h1 tabindex="-1">${title}</h1><p>${text}</p></div>`;
export function groups(){return `<section class="inner-page groups-page">${intro('02','ROBLOX','Games. Groups.<br><em>Good company.</em>','Two spaces for the things I build on Roblox. Explore the communities and their games.')}<div class="group-showcase">${C.groups.map(g=>groupCard(g,true)).join('')}</div><div class="page-note">${icon('game')}<span>More experiences will appear here as they become public.</span>${ext(C.links.roblox,'My Roblox profile '+icon('external'),'tiny-link')}</div></section>`;}
export function projects(){return `<section class="inner-page projects-page">${intro('03','BEYOND THE MAIN PROJECT','More than<br><em>one idea.</em>','A place for the next games, addons and systems. On Roblox and beyond.')}<div class="future-grid">${C.upcoming.map((p,i)=>`<article class="future-card material"><span class="future-number">0${i+1}</span><div class="future-object object-${i}">${icon(p.icon)}</div><span class="pill">COMING SOON</span><h2>${p.name}</h2><p>${p.description}</p><span class="micro">${p.type}</span></article>`).join('')}</div><div class="page-note">${icon('spark')}<span>Nothing announced yet. Follow along for what comes next.</span>${ext(C.links.youtube,'Follow on YouTube '+icon('external'),'tiny-link')}</div></section>`;}
export function about(){return `<section class="inner-page about-page"><div class="about-grid"><div>${intro('04','THE PERSON BEHIND IT','Who is<br><em>DXT?!</em>','A creator with cars on the mind and projects in the making.')}<div class="biography"><p>I’m DXT, the developer behind <strong>Berserk Drift X</strong>. This is my personal space for the things I create, the communities around them and the ideas I’m exploring.</p><p>My main project lives on Roblox. What comes next can go beyond it: games, addons, systems and new experiments.</p><div class="bio-tags"><span>${icon('wheel')}Car culture</span><span>${icon('game')}Game development</span><span>${icon('code')}New ideas</span></div>${ext(C.links.roblox,`Meet me on Roblox ${icon('external')}`,'button outline material')}</div></div><div class="identity-stage"><div class="logo-model" id="logo-model"><img src="/assets/icons/dxt.webp" alt="DXT logo"><canvas id="logo-canvas" aria-label="Interactive 3D DXT logo" tabindex="0"></canvas><span class="micro model-hint">DXT / ORIGINAL 3D MARK</span></div><a class="profile-card material" href="${C.links.roblox}" target="_blank" rel="noopener noreferrer"><img data-avatar class="profile-avatar" src="/assets/images/avatar.webp" alt="DXT Roblox avatar"><span><small>ROBLOX PROFILE</small><strong data-profile-name>DXT</strong><span class="micro" data-profile-handle>VIEW MY PROFILE</span></span>${icon('external')}</a></div></div></section>`;}
export function contact(){return `<section class="inner-page contact-page">${intro('05','SOCIALS & CONTACT','Let’s<br><em>connect.</em>','A project, an idea, or just a conversation. Find me here.')}<div class="contact-layout"><div class="contact-links">${socialItems.map(([key,title,sub],i)=>ext(C.links[key],`<span class="contact-number">0${i+1}</span>${icon(key)}<span><strong>${title}</strong><small>${sub}</small></span>${icon('external')}`,'contact-row material')).join('')}</div><aside class="contact-brand"><img src="/assets/icons/dxt.webp" alt="DXT"><p>THE NEXT CHAPTER<br>STARTS WITH<br><em>A CONVERSATION.</em><span class="micro">PERSONAL SPACE / DXT</span></p></aside></div></section>`;}
export function notFound(){return `<section class="inner-page">${intro('404','WRONG TURN','Off the<br><em>track.</em>','This page does not exist. Let’s get you back to the main project.')}<a href="/" data-route class="button primary material">Back to Berserk ${icon('arrow')}</a></section>`;}
export const pages={home,groups,projects,about,contact,'not-found':notFound};
