import * as T from 'three';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
import {RectAreaLightUniformsLib} from 'three/addons/lights/RectAreaLightUniformsLib.js';
import {buildCar} from './car.js';
import {loadShowroomCar} from './room-car.js';
import {buildShowroom,createReferenceCamera} from './room-environment.js';
import {RoomOptics} from './room-optics.js';
import {renderBudget,panelIndex} from './room-core.js';
import {ROOM_PANELS} from '../pages/home-room.js';
import {roomVertex,smokeFragment,beamFragment} from './room-shaders.js';
import {elapsedFrameTime,advance,clamp} from '../core.js';

/** Real room geometry, five independently projected screens, a detailed car and a mirrored-camera floor. */
export class HeroScene {
 constructor(canvas,settings){
  Object.assign(this,{canvas,settings,host:canvas.closest('.room-hero'),controller:new AbortController(),disposed:false,raf:0,time:0,frames:0,yaw:0,targetYaw:0,pitch:0,targetPitch:0,lookX:0,targetLookX:0,activePanel:0,hoverPanel:-1,drag:null});
  this.pointer=new T.Vector2();this.targetPointer=new T.Vector2();this.reduced=matchMedia('(prefers-reduced-motion: reduce)');
  this.renderer=new T.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});this.gl=this.renderer.getContext();this.renderer.outputColorSpace=T.SRGBColorSpace;this.renderer.toneMapping=T.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.05;this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=T.PCFSoftShadowMap;this.renderer.shadowMap.autoUpdate=false;this.renderer.setClearColor(0x030305);this.renderer.info.autoReset=false;
  this.scene=new T.Scene();this.scene.background=new T.Color(0x030305);this.scene.fog=new T.FogExp2(0x101015,.013);this.referenceCamera=createReferenceCamera();this.camera=this.referenceCamera.clone();this.cameraTarget=new T.Vector3(0,2.31,0);
  const pmrem=new T.PMREMGenerator(this.renderer),room=new RoomEnvironment();this.environment=pmrem.fromScene(room,.018);this.scene.environment=this.environment.texture;this.scene.environmentIntensity=.34;this.scene.environmentRotation.y=.2;room.dispose();pmrem.dispose();
  buildShowroom(this);this.buildLights();this.buildAtmosphere();this.buildVehicle();this.optics=new RoomOptics(this.renderer,this.scene,this.camera);this.composer=this.optics.composer;
  this.raycaster=new T.Raycaster();this.pickPosition=new T.Vector2();this.panelLinks=[...this.host.querySelectorAll('.room-panel-link')];this.bind();this.resizeObserver=new ResizeObserver(()=>this.resize());this.resizeObserver.observe(this.host);
  this.setSettings();this.resize();this.ready=true;this.host.classList.add('scene-ready');this.host.dataset.sceneStatus='ready';this.selectPanel(0);this.wake();
 }
 buildVehicle(){
  this.carPivot=new T.Group();this.carPivot.position.set(-.67248,-.084365,1.28199);this.carPivot.rotation.y=-.460715;this.carPivot.scale.setScalar(1.922749);this.scene.add(this.carPivot);this.red=buildCar({color:0xc90013});this.carPivot.add(this.red);this.modelReady=false;
  loadShowroomCar().then(car=>{if(this.disposed){car.traverse(o=>{o.geometry?.dispose();o.material?.dispose?.();});return;}this.carPivot.remove(this.red);const gs=new Set(),ms=new Set();this.red.traverse(o=>{if(o.geometry)gs.add(o.geometry);if(o.material)ms.add(o.material);});gs.forEach(g=>g.dispose());ms.forEach(m=>m.dispose());this.red=car;this.carPivot.add(car);this.modelReady=true;this.renderer.shadowMap.needsUpdate=true;this.wake();}).catch(e=>{this.modelError=e.message;console.warn('[DXT] Detailed model unavailable; authored geometry remains available.',e);this.wake();});
 }
 buildLights(){
  RectAreaLightUniformsLib.init();this.scene.add(new T.HemisphereLight(0xcbd4e2,0x160c0e,.27));this.key=new T.DirectionalLight(0xfff1e8,2.6);this.key.position.set(-3.5,8,-4);this.key.castShadow=true;Object.assign(this.key.shadow.camera,{left:-8,right:8,top:8,bottom:-8,near:.5,far:26});this.key.shadow.bias=-.00025;this.key.shadow.normalBias=.012;this.key.shadow.mapSize.set(1536,1536);this.scene.add(this.key);
  for(const [color,intensity,w,h,p,target]of [[0xf8f6ff,15,8,1.15,[-2,6.1,-3.5],[0,.65,0]],[0xfff7f4,9,5,1.1,[4,4.7,-2],[0,.8,0]],[0xff0923,9.5,8,.7,[0,2.8,4],[0,.65,0]],[0xff1a25,7,5,1.3,[-5,2.8,-.5],[0,.7,0]],[0xe4eafa,4,3,3,[6.5,3.5,0],[0,1,0]]]){const l=new T.RectAreaLight(color,intensity,w,h);l.position.set(...p);l.lookAt(...target);this.scene.add(l);}
  const spot=new T.SpotLight(0xe8efff,70,22,.28,.65,2);spot.position.set(0,7.45,.1);spot.target.position.set(0,0,0);this.scene.add(spot,spot.target);this.renderer.shadowMap.needsUpdate=true;
 }
 buildAtmosphere(){
  this.smokes=[];let seed=829;const random=()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296;};
  for(let i=0;i<28;i++){const x=(i%2?1:-1)*(2.7+random()*2),z=-1+random()*3.8,y=.4+random()*.8;const material=new T.ShaderMaterial({vertexShader:roomVertex,fragmentShader:smokeFragment,uniforms:{time:{value:0},seed:{value:random()*19},density:{value:.56+random()*.32},tint:{value:new T.Color(i%4===0?0x916367:0x90939c)}},transparent:true,depthWrite:false,side:T.DoubleSide});const mesh=new T.Mesh(new T.PlaneGeometry(2.2+random()*1.3,1.5+random()*.8),material);mesh.position.set(x,y,z);mesh.userData.base=mesh.position.clone();mesh.userData.phase=random()*6.28;mesh.renderOrder=3;this.scene.add(mesh);this.smokes.push(mesh);}
  this.beams=[];for(let i=0;i<5;i++){const material=new T.ShaderMaterial({vertexShader:roomVertex,fragmentShader:beamFragment,uniforms:{time:{value:0}},transparent:true,depthWrite:false,side:T.DoubleSide,blending:T.AdditiveBlending});const mesh=new T.Mesh(new T.PlaneGeometry(4.1,7.4),material);mesh.position.set(0,3.9,.65+i*.35);mesh.renderOrder=4;this.scene.add(mesh);this.beams.push(mesh);}
  const p=[];for(let i=0;i<190;i++)p.push((random()-.5)*10,.25+random()*6.4,(random()-.5)*6);const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(p,3));this.dust=new T.Points(g,new T.PointsMaterial({color:0xb8bdc9,size:.012,transparent:true,opacity:.33,depthWrite:false}));this.scene.add(this.dust);
 }
 bind(){
  const on=(el,event,handler,options={})=>el?.addEventListener(event,handler,{...options,signal:this.controller.signal});
  on(this.canvas,'pointermove',e=>{const r=this.canvas.getBoundingClientRect();this.targetPointer.set((e.clientX-r.left)/r.width*2-1,1-(e.clientY-r.top)/r.height*2);if(this.drag&&this.drag.id===e.pointerId){this.drag.moved ||= Math.hypot(e.clientX-this.drag.startX,e.clientY-this.drag.startY)>7;this.targetYaw=clamp(this.targetYaw-(e.clientX-this.drag.x)*.002,-.46,.46);this.targetPitch=clamp(this.targetPitch+(e.clientY-this.drag.y)*.0021,-.18,.21);this.drag.x=e.clientX;this.drag.y=e.clientY;this.hoverPanel=-1;}else this.hoverPanel=this.pick(e.clientX,e.clientY);this.canvas.style.cursor=this.drag?'grabbing':this.hoverPanel>=0?'pointer':'grab';this.wake();},{passive:true});
  on(this.canvas,'pointerdown',e=>{if(e.button!==0)return;this.drag={id:e.pointerId,x:e.clientX,y:e.clientY,startX:e.clientX,startY:e.clientY,moved:false};this.canvas.setPointerCapture(e.pointerId);this.canvas.classList.add('dragging');this.wake();});
  on(this.canvas,'pointerup',e=>{const click=this.drag&&this.drag.id===e.pointerId&&!this.drag.moved,hit=click?this.pick(e.clientX,e.clientY):-1;this.release();if(hit>=0)this.panelLinks[hit]?.click();});on(this.canvas,'pointercancel',()=>this.release());on(this.canvas,'lostpointercapture',()=>{this.drag=null;this.canvas.classList.remove('dragging');});on(this.canvas,'pointerleave',()=>{if(!this.drag){this.hoverPanel=-1;this.targetPointer.set(0,0);}this.wake();});
  on(this.canvas,'keydown',e=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Home','Enter'].includes(e.key))e.preventDefault();if(e.key==='ArrowLeft')this.focusPanel(this.activePanel-1);if(e.key==='ArrowRight')this.focusPanel(this.activePanel+1);if(e.key==='ArrowUp')this.targetPitch=clamp(this.targetPitch+.05,-.18,.21);if(e.key==='ArrowDown')this.targetPitch=clamp(this.targetPitch-.05,-.18,.21);if(e.key==='Home'||e.key==='Escape')this.reset();if(e.key==='Enter')this.panelLinks[this.activePanel]?.click();this.wake();});
  on(document,'click',e=>{const b=e.target.closest('[data-focus-panel]');if(b)this.focusPanel(Number(b.dataset.focusPanel));});this.panelLinks.forEach((a,i)=>{on(a,'focus',()=>this.focusPanel(i));on(a,'blur',()=>{this.hoverPanel=-1;this.wake();});});
  on(document,'visibilitychange',()=>{if(document.hidden){this.sleep();this.audio?.suspend();}else{if(this.settings.sound)this.audio?.resume();this.wake();}});on(this.reduced,'change',()=>this.setSettings());on(this.canvas,'webglcontextlost',e=>{e.preventDefault();this.lost=true;this.sleep();this.audio?.suspend();this.host.classList.remove('scene-ready');this.host.classList.add('scene-unavailable');this.host.dataset.sceneStatus='unavailable';});on(this.canvas,'webglcontextrestored',()=>{this.lost=false;this.renderer.shadowMap.needsUpdate=true;this.host.classList.remove('scene-unavailable');this.host.classList.add('scene-ready');this.host.dataset.sceneStatus='ready';if(this.settings.sound)this.audio?.resume();this.setSettings();});
 }
 release(){if(this.drag&&this.canvas.hasPointerCapture(this.drag.id))this.canvas.releasePointerCapture(this.drag.id);this.drag=null;this.canvas.classList.remove('dragging');}
 pick(x,y){const r=this.canvas.getBoundingClientRect();this.pickPosition.set((x-r.left)/r.width*2-1,1-(y-r.top)/r.height*2);this.raycaster.setFromCamera(this.pickPosition,this.camera);const hits=this.raycaster.intersectObjects([...this.panels.map(p=>p.screen),this.carPivot],true);return hits.length&&Number.isInteger(hits[0].object.userData.panel)?hits[0].object.userData.panel:-1;}
 selectPanel(i){
  this.activePanel=panelIndex(i);const panel=ROOM_PANELS[this.activePanel];this.host.dataset.activePanel=this.activePanel;document.querySelectorAll('[data-focus-panel]').forEach(b=>{const active=Number(b.dataset.focusPanel)===this.activePanel;b.classList.toggle('is-active',active);b.setAttribute('aria-pressed',String(active));});
  const title=this.host.querySelector('[data-active-panel-title]'),number=this.host.querySelector('[data-active-panel-number]'),a=this.host.querySelector('[data-active-panel-open]');if(title)title.textContent=panel.title;if(number)number.innerHTML=`0${this.activePanel+1} <span>/ 05</span>`;if(a){a.href=panel.href;a.querySelector('span').textContent=panel.action;a.setAttribute('aria-label',`${panel.action}: ${panel.title}`);if(panel.external){a.target='_blank';a.rel='noopener noreferrer';a.removeAttribute('data-route');}else{a.removeAttribute('target');a.removeAttribute('rel');a.dataset.route='';}}
 }
 focusPanel(i){this.selectPanel(i);const mobile=this.width<741;this.targetLookX=this.panels[this.activePanel].center.x*(mobile?.85:.30);this.targetYaw=(2-this.activePanel)*(mobile?.14:.06);this.targetPitch=0;this.hoverPanel=this.activePanel;this.wake();}
 reset(){this.targetYaw=0;this.targetPitch=0;this.targetLookX=0;this.targetPointer.set(0,0);this.hoverPanel=-1;this.selectPanel(0);this.wake();}
 async setSound(enabled){
  if(!enabled){if(this.audio)await this.audio.suspend();return false;}
  if(!this.audio){const Audio=window.AudioContext||window.webkitAudioContext;if(!Audio)return false;this.audio=new Audio();const master=this.audio.createGain();master.gain.value=.027;master.connect(this.audio.destination);for(const [f,g]of [[43,.32],[86,.17],[129,.065]]){const o=this.audio.createOscillator(),gain=this.audio.createGain();o.type='sine';o.frequency.value=f;gain.gain.value=g;o.connect(gain).connect(master);o.start();}const b=this.audio.createBuffer(1,this.audio.sampleRate*3,this.audio.sampleRate),c=b.getChannelData(0);for(let i=0;i<c.length;i++)c[i]=(Math.random()*2-1)*.17;const n=this.audio.createBufferSource();n.buffer=b;n.loop=true;const filter=this.audio.createBiquadFilter();filter.type='lowpass';filter.frequency.value=350;n.connect(filter).connect(master);n.start();}await this.audio.resume();return true;
 }
 setSettings(){if(!this.renderer)return;this.optics?.setQuality(this.settings.quality);this.renderer.shadowMap.enabled=this.settings.quality!=='low';this.renderer.shadowMap.needsUpdate=true;this.resize();this.wake();}
 resize(){if(this.disposed||!this.optics)return;const w=this.host.clientWidth,h=this.host.clientHeight;if(w<2||h<2)return;this.width=w;this.height=h;const b=renderBudget(w,h,devicePixelRatio||1,this.settings.quality);this.budget=b;this.renderer.setPixelRatio(b.ratio);this.renderer.setSize(w,h,false);this.optics.resize(w,h,b.ratio);this.camera.aspect=w/h;this.camera.fov=w<741?42:38;this.camera.updateProjectionMatrix();this.ground.getRenderTarget().setSize(b.reflection,b.reflection);this.ground.material.uniforms.reflectionResolution.value.set(b.reflection,b.reflection);this.updateCamera();this.updateLinkProjection();this.wake();}
 updateCamera(){const mobile=this.width<741,r=mobile?23.5:13.6,micro=this.reduced.matches?0:this.pointer.x*.006;this.camera.position.set(Math.sin(this.yaw+micro)*r,1.48+this.pitch*3.4+(mobile?.4:0),-Math.cos(this.yaw+micro)*r);this.cameraTarget.set(this.lookX,2.31+(mobile?-.05:0),0);this.camera.lookAt(this.cameraTarget);this.camera.updateMatrixWorld(true);}
 updateLinkProjection(){if(!this.panelLinks)return;this.panels.forEach((p,i)=>{const points=p.corners.map(p=>{const q=p.clone().project(this.camera);return [(q.x*.5+.5)*this.width,(-q.y*.5+.5)*this.height];}),xs=points.map(p=>p[0]),ys=points.map(p=>p[1]),left=Math.min(...xs),top=Math.min(...ys),w=Math.max(...xs)-left,h=Math.max(...ys)-top,a=this.panelLinks[i];if(a)Object.assign(a.style,{left:`${left}px`,top:`${top}px`,width:`${w}px`,height:`${h}px`,clipPath:`polygon(${points.map(([x,y])=>`${(x-left)/w*100}% ${(y-top)/h*100}%`).join(',')})`,pointerEvents:'none'});});}
 wake(){if(this.disposed||this.raf||document.hidden||this.lost)return;this.last=performance.now();this.raf=requestAnimationFrame(t=>this.frame(t));}
 sleep(){cancelAnimationFrame(this.raf);this.raf=0;}
 frame(now){
  this.raf=0;if(this.disposed||this.lost||document.hidden)return;const dt=elapsedFrameTime(now,this.last);this.last=now;const animated=!this.settings.paused&&!this.reduced.matches;if(animated)this.time+=Math.min(.05,dt);const before=this.camera.position.clone();this.yaw=advance(this.yaw,this.targetYaw,7,dt);this.pitch=advance(this.pitch,this.targetPitch,7,dt);this.lookX=advance(this.lookX,this.targetLookX,7,dt);this.pointer.lerp(this.targetPointer,1-Math.exp(-4*dt));this.updateCamera();const motion=Math.max(before.distanceTo(this.camera.position),Math.abs(this.targetLookX-this.lookX)*.1);let hovering=false;
  for(const p of this.panels){p.hover=advance(p.hover,p.index===this.hoverPanel?1:0,8,dt);p.material.uniforms.hover.value=p.hover;p.hoverLight.intensity=p.hover*1.3;if(Math.abs(p.hover-(p.index===this.hoverPanel?1:0))>.001)hovering=true;}
  for(const m of this.smokes){m.quaternion.copy(this.camera.quaternion);m.material.uniforms.time.value=this.time;m.position.x=m.userData.base.x+Math.sin(this.time*.18+m.userData.phase)*.23;m.position.y=m.userData.base.y+Math.sin(this.time*.23+m.userData.phase)*.07;}for(const b of this.beams){b.quaternion.copy(this.camera.quaternion);b.material.uniforms.time.value=this.time;}
  this.dust.rotation.y=this.time*.009;this.ground.material.uniforms.time.value=this.time;this.renderer.info.reset();this.optics.render(dt,{time:this.time,motion,focusDistance:this.camera.position.distanceTo(new T.Vector3(0,1.25,-.4)),paused:!animated});this.frames++;if(motion>.00001||this.frames<3)this.updateLinkProjection();
  if(animated||this.drag||hovering||motion>.00001||Math.abs(this.yaw-this.targetYaw)>.0001||Math.abs(this.pitch-this.targetPitch)>.0001||Math.abs(this.lookX-this.targetLookX)>.0001||this.pointer.distanceTo(this.targetPointer)>.001)this.raf=requestAnimationFrame(t=>this.frame(t));
 }
 inspect(){let carTriangles=0;this.carPivot.traverse(o=>{if(o.isMesh)carTriangles+=(o.geometry.index?.count??o.geometry.attributes.position.count)/3;});return {ready:this.ready,modelReady:this.modelReady,modelError:this.modelError??null,renderer:'Three.js r180 / WebGL2',geometry:'volumetric car and architecture',panels:this.panels.length,cars:1,carTriangles,frames:this.frames,yaw:this.yaw,pitch:this.pitch,activePanel:this.activePanel,hoverPanel:this.hoverPanel,width:this.canvas.width,height:this.canvas.height,drawCalls:this.renderer.info.render.calls,triangles:this.renderer.info.render.triangles,quality:this.settings.quality,reflection:'mirrored camera / rough wet surface',postprocessing:'depth of field, camera motion, HDR bloom, streaks, analytic grade',glError:this.gl.getError()};}
 dispose(){if(this.disposed)return;this.disposed=true;this.sleep();this.release();this.controller.abort();this.resizeObserver.disconnect();this.audio?.close();const gs=new Set(),ms=new Set(),ts=new Set(this.textures);this.scene.traverse(o=>{if(o.geometry)gs.add(o.geometry);if(o.material)(Array.isArray(o.material)?o.material:[o.material]).forEach(m=>{ms.add(m);for(const v of Object.values(m))if(v?.isTexture)ts.add(v);});});gs.forEach(g=>g.dispose());ms.forEach(m=>m.dispose());ts.forEach(t=>t.dispose());this.ground.dispose();this.environment.dispose();this.key.shadow.dispose();this.optics.dispose();this.renderer.dispose();}
}
