export const FULLSCREEN=`#version 300 es
precision highp float;out vec2 uv;void main(){vec2 p=vec2(float((gl_VertexID<<1)&2),float(gl_VertexID&2));uv=p;gl_Position=vec4(p*2.-1.,0.,1.);}`;
export class Program{
 constructor(gl,vertex,fragment){this.gl=gl;this.uniforms=new Map();const compile=(kind,source)=>{const s=gl.createShader(kind);gl.shaderSource(s,source);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS)){const e=gl.getShaderInfoLog(s);gl.deleteShader(s);throw Error(e);}return s;};const v=compile(gl.VERTEX_SHADER,vertex),f=compile(gl.FRAGMENT_SHADER,fragment);this.handle=gl.createProgram();gl.attachShader(this.handle,v);gl.attachShader(this.handle,f);gl.linkProgram(this.handle);gl.deleteShader(v);gl.deleteShader(f);if(!gl.getProgramParameter(this.handle,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(this.handle));}
 use(){this.gl.useProgram(this.handle);return this;}
 set(name,value){const g=this.gl;let u=this.uniforms.get(name);if(u===undefined){u=g.getUniformLocation(this.handle,name);this.uniforms.set(name,u);}if(u===null)return this;if(typeof value==='number')g.uniform1f(u,value);else if(value.length===16)g.uniformMatrix4fv(u,false,value);else if(value.length===2)g.uniform2fv(u,value);else if(value.length===3)g.uniform3fv(u,value);else if(value.length===4)g.uniform4fv(u,value);return this;}
 sampler(name,unit){const g=this.gl;let u=this.uniforms.get(name);if(u===undefined){u=g.getUniformLocation(this.handle,name);this.uniforms.set(name,u);}if(u!==null)g.uniform1i(u,unit);return this;}
 dispose(){this.gl.deleteProgram(this.handle);}
}
export function target(gl,w,h,hdr){const texture=gl.createTexture(),framebuffer=gl.createFramebuffer();gl.bindTexture(gl.TEXTURE_2D,texture);gl.texImage2D(gl.TEXTURE_2D,0,hdr?gl.RGBA16F:gl.RGBA8,w,h,0,gl.RGBA,hdr?gl.HALF_FLOAT:gl.UNSIGNED_BYTE,null);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);gl.bindFramebuffer(gl.FRAMEBUFFER,framebuffer);gl.framebufferTexture2D(gl.FRAMEBUFFER,gl.COLOR_ATTACHMENT0,gl.TEXTURE_2D,texture,0);if(gl.checkFramebufferStatus(gl.FRAMEBUFFER)!==gl.FRAMEBUFFER_COMPLETE){gl.deleteTexture(texture);gl.deleteFramebuffer(framebuffer);throw Error('Optical framebuffer unavailable');}return {w,h,texture,framebuffer,dispose(){gl.deleteTexture(texture);gl.deleteFramebuffer(framebuffer);}};}
export function bind(gl,texture,unit=0){gl.activeTexture(gl.TEXTURE0+unit);gl.bindTexture(gl.TEXTURE_2D,texture);}
export async function imageTexture(gl,src){const im=new Image();im.decoding='async';im.src=src;await im.decode();const t=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,t);gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL,true);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,gl.RGBA,gl.UNSIGNED_BYTE,im);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR_MIPMAP_LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);gl.generateMipmap(gl.TEXTURE_2D);const a=gl.getExtension('EXT_texture_filter_anisotropic');if(a)gl.texParameterf(gl.TEXTURE_2D,a.TEXTURE_MAX_ANISOTROPY_EXT,Math.min(4,gl.getParameter(a.MAX_TEXTURE_MAX_ANISOTROPY_EXT)));return{texture:t,width:im.naturalWidth,height:im.naturalHeight};}
export const BLUR=`#version 300 es
precision highp float;in vec2 uv;uniform sampler2D source;uniform vec2 stepSize;uniform float extract;out vec4 color;void main(){vec3 c=texture(source,uv).rgb*.227027;for(int i=1;i<=4;i++){float w=i==1?.1945946:i==2?.1216216:i==3?.054054:.016216;c+=(texture(source,uv+float(i)*stepSize).rgb+texture(source,uv-float(i)*stepSize).rgb)*w;}if(extract>.5){float l=max(c.r,max(c.g,c.b));c*=max(l-.78,0.)/max(l,.001);}color=vec4(c,1.);}`;
export const OUTPUT=`#version 300 es
precision highp float;in vec2 uv;uniform sampler2D source,bloom;out vec4 color;vec3 aces(vec3 c){return clamp((c*(2.51*c+.03))/(c*(2.43*c+.59)+.14),0.,1.);}void main(){vec3 c=texture(source,uv).rgb+texture(bloom,uv).rgb*.43;color=vec4(pow(aces(c),vec3(1./2.2)),1.);}`;
export class Optics{
 constructor(gl){this.gl=gl;this.hdr=!!gl.getExtension('EXT_color_buffer_float');this.blur=new Program(gl,FULLSCREEN,BLUR);this.output=new Program(gl,FULLSCREEN,OUTPUT);this.targets=[];}
 resize(w,h){this.targets.forEach(t=>t.dispose());this.targets=[];const allocate=()=>{this.scene=target(this.gl,w,h,this.hdr);this.targets.push(this.scene);this.a=target(this.gl,Math.max(2,Math.ceil(w/3)),Math.max(2,Math.ceil(h/3)),this.hdr);this.targets.push(this.a);this.b=target(this.gl,this.a.w,this.a.h,this.hdr);this.targets.push(this.b);};try{allocate();}catch{this.targets.forEach(t=>t.dispose());this.targets=[];this.hdr=false;allocate();}}
 set(t){const g=this.gl;g.bindFramebuffer(g.FRAMEBUFFER,t?.framebuffer??null);g.viewport(0,0,t?.w??g.canvas.width,t?.h??g.canvas.height);}
 draw(){this.gl.bindVertexArray(null);this.gl.drawArrays(this.gl.TRIANGLES,0,3);}
 finish(){const g=this.gl;g.disable(g.DEPTH_TEST);g.disable(g.CULL_FACE);g.disable(g.BLEND);this.set(this.a);bind(g,this.scene.texture);this.blur.use().sampler('source',0).set('stepSize',[1/this.scene.w,0]).set('extract',1);this.draw();this.set(this.b);bind(g,this.a.texture);this.blur.use().set('stepSize',[0,1/this.a.h]).set('extract',0);this.draw();this.set(null);bind(g,this.scene.texture);bind(g,this.b.texture,1);this.output.use().sampler('source',0).sampler('bloom',1);this.draw();}
 dispose(){this.targets.forEach(t=>t.dispose());this.blur.dispose();this.output.dispose();}
}
