import {Program,FULLSCREEN,Optics} from './gl.js';import {qualitySize,advance} from '../core.js';import {parseLogoGLB} from './glb.js';
const VERTEX=`#version 300 es
precision highp float;layout(location=0)in vec3 position;layout(location=1)in vec3 normal;uniform vec2 rotation;uniform float aspect;out vec3 world,norm;
mat3 rot(){float a=rotation.x,b=rotation.y;mat3 ry=mat3(cos(a),0.,-sin(a),0.,1.,0.,sin(a),0.,cos(a));mat3 rx=mat3(1.,0.,0.,0.,cos(b),sin(b),0.,-sin(b),cos(b));return rx*ry;}
void main(){world=rot()*position;norm=rot()*normal;float z=4.1-world.z;gl_Position=vec4(world.x*2.5/aspect,world.y*2.5,(z-3.9)*.7,z);}`;
const FRAGMENT=`#version 300 es
precision highp float;in vec3 world,norm;uniform float material;out vec4 color;
void main(){vec3 n=normalize(norm),v=normalize(vec3(0,0,4.1)-world);if(!gl_FrontFacing)n=-n;vec3 r=reflect(-v,n);float fres=pow(1.-max(dot(n,v),0.),3.);
vec3 base=material>.5?vec3(.70,.68,.66):vec3(.055,.034,.024);vec3 c=base*.18;
vec3 l=normalize(vec3(-2.5,4.,3.8)-world);float diffuse=max(dot(n,l),0.);float spec=pow(max(dot(n,normalize(l+v)),0.),material>.5?60.:130.);c+=base*diffuse*.8+vec3(1.5,1.4,1.3)*spec;
l=normalize(vec3(3.,.4,1.7)-world);c+=vec3(1.,.15,.018)*(base*max(dot(n,l),0.)*.4+pow(max(dot(n,normalize(l+v)),0.),35.)*1.5);
float stripe=exp(-pow((r.y-.32)/.12,2.))+exp(-pow((r.x+.52)/.045,2.))*.7;
c+=mix(vec3(.52,.60,.72),vec3(1.,.20,.03),smoothstep(-.2,.5,r.x))*stripe*(.12+fres*.85);
c+=vec3(1.,.11,.008)*fres*.32;color=vec4(c,1.);}`;
const BG=`#version 300 es
precision highp float;in vec2 uv;out vec4 color;void main(){vec2 p=(uv-.5)*vec2(1.4,1.);float glow=exp(-dot(p,p)*6.);float grid=pow(max(0.,1.-min(abs(fract(uv.x*22.)-.5),abs(fract(uv.y*14.)-.5))*100.),3.);vec3 c=vec3(.002,.002,.003)+vec3(.023,.003,.0004)*glow+cmax(0.);color=vec4(c,1.);}`.replace('+cmax(0.)','+vec3(.003,.001,.0005)*grid*glow');
export class LogoScene{
 constructor(canvas,settings){this.canvas=canvas;this.settings=settings;this.ready=false;this.dead=false;this.raf=0;this.frames=0;this.rotation=[Math.PI-.15,.10];this.target=[Math.PI-.15,.10];this.abort=new AbortController();this.reduced=matchMedia('(prefers-reduced-motion: reduce)');const on=(a,t,f)=>a.addEventListener(t,f,{signal:this.abort.signal});
 on(canvas,'pointerdown',e=>{if(e.button!==0)return;this.drag={id:e.pointerId,x:e.clientX,y:e.clientY};canvas.setPointerCapture(e.pointerId);canvas.style.cursor='grabbing';this.wake();});on(canvas,'pointermove',e=>{if(!this.drag||this.drag.id!==e.pointerId)return;this.target[0]+=(e.clientX-this.drag.x)*.008;this.target[1]+=(e.clientY-this.drag.y)*.008;this.drag.x=e.clientX;this.drag.y=e.clientY;this.wake();});
 const clear=()=>{this.drag=null;canvas.style.cursor='grab';};on(canvas,'pointerup',e=>{if(canvas.hasPointerCapture(e.pointerId))canvas.releasePointerCapture(e.pointerId);clear();});on(canvas,'pointercancel',clear);on(canvas,'lostpointercapture',clear);
 on(canvas,'keydown',e=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Home'].includes(e.key))return;e.preventDefault();if(e.key==='Home')this.target=[Math.PI-.15,.1];else this.target[e.key==='ArrowLeft'||e.key==='ArrowRight'?0:1]+=(e.key==='ArrowLeft'||e.key==='ArrowUp'?-.18:.18);this.wake();});
 on(document,'visibilitychange',()=>document.hidden?this.sleep():this.wake());on(this.reduced,'change',()=>this.wake());on(canvas,'webglcontextlost',e=>{e.preventDefault();this.ready=false;canvas.style.opacity=0;this.sleep();});on(canvas,'webglcontextrestored',()=>this.initialize());
 this.ro=new ResizeObserver(()=>{this.dirty=true;this.wake();});this.ro.observe(canvas);this.initialize();}
 async initialize(){try{const gl=this.gl=this.canvas.getContext('webgl2',{alpha:false,antialias:false});if(!gl)throw Error('WebGL2 unavailable');const r=await fetch('/assets/models/dxt-logo.glb');if(!r.ok)throw Error('Logo model unavailable');const data=parseLogoGLB(await r.arrayBuffer());if(this.dead)return;this.triangles=data.triangles;this.program=new Program(gl,VERTEX,FRAGMENT);this.bg=new Program(gl,FULLSCREEN,BG);this.optics=new Optics(gl);this.meshes=data.meshes.map(m=>{const vao=gl.createVertexArray(),buffers=[];gl.bindVertexArray(vao);for(const [i,a]of[m.positions,m.normals].entries()){const b=gl.createBuffer();buffers.push(b);gl.bindBuffer(gl.ARRAY_BUFFER,b);gl.bufferData(gl.ARRAY_BUFFER,a,gl.STATIC_DRAW);gl.enableVertexAttribArray(i);gl.vertexAttribPointer(i,3,gl.FLOAT,false,0,0);}const b=gl.createBuffer();buffers.push(b);gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,b);gl.bufferData(gl.ELEMENT_ARRAY_BUFFER,m.indices,gl.STATIC_DRAW);return{vao,buffers,count:m.indices.length,material:m.material};});this.ready=true;this.dirty=true;this.wake();}catch(e){this.error=e.message;this.canvas.style.opacity=0;console.warn('[DXT] Logo fallback:',e.message);}}
 wake(){if(this.raf||!this.ready||this.dead||document.hidden)return;this.last=performance.now();this.raf=requestAnimationFrame(t=>this.frame(t));}sleep(){cancelAnimationFrame(this.raf);this.raf=0;}setSettings(){this.dirty=true;this.wake();}
 frame(now){this.raf=0;if(!this.ready||this.dead||document.hidden)return;const dt=Math.min(.05,(now-this.last)/1000);this.last=now;const animate=!this.settings.paused&&!this.reduced.matches;if(animate&&!this.drag)this.target[0]+=dt*.07;for(let i=0;i<2;i++)this.rotation[i]=advance(this.rotation[i],this.target[i],8,dt);
 const g=this.gl;if(this.dirty){const r=this.canvas.getBoundingClientRect(),[w,h]=qualitySize(r.width,r.height,devicePixelRatio,this.settings.quality);this.canvas.width=w;this.canvas.height=h;this.optics.resize(w,h);if(this.depth)g.deleteRenderbuffer(this.depth);this.depth=g.createRenderbuffer();g.bindRenderbuffer(g.RENDERBUFFER,this.depth);g.renderbufferStorage(g.RENDERBUFFER,g.DEPTH_COMPONENT16,w,h);g.bindFramebuffer(g.FRAMEBUFFER,this.optics.scene.framebuffer);g.framebufferRenderbuffer(g.FRAMEBUFFER,g.DEPTH_ATTACHMENT,g.RENDERBUFFER,this.depth);this.dirty=false;}
 this.optics.set(this.optics.scene);g.disable(g.DEPTH_TEST);g.disable(g.BLEND);this.bg.use();this.optics.draw();g.enable(g.DEPTH_TEST);g.depthMask(true);g.clearDepth(1);g.clear(g.DEPTH_BUFFER_BIT);g.disable(g.CULL_FACE);this.program.use().set('rotation',this.rotation).set('aspect',this.canvas.width/this.canvas.height);for(const m of this.meshes){this.program.set('material',m.material);g.bindVertexArray(m.vao);g.drawElements(g.TRIANGLES,m.count,g.UNSIGNED_INT,0);}this.optics.finish();this.canvas.style.opacity=1;this.frames++;if(animate||this.rotation.some((v,i)=>Math.abs(v-this.target[i])>.001))this.raf=requestAnimationFrame(t=>this.frame(t));}
 inspect(){return{type:'glb-mesh',ready:this.ready,triangles:this.triangles??0,frames:this.frames,scheduled:!!this.raf,error:this.error??null};}
 dispose(){this.dead=true;this.sleep();this.abort.abort();this.ro.disconnect();this.program?.dispose();this.bg?.dispose();this.optics?.dispose();for(const m of this.meshes??[]){this.gl.deleteVertexArray(m.vao);for(const b of m.buffers)this.gl.deleteBuffer(b);}if(this.depth)this.gl.deleteRenderbuffer(this.depth);}
}
