import {PerspectiveCards} from './ui/perspective-cards.js';
import {CONTENT,navigation as nav} from './content.js';import {pages} from './pages/templates.js';import {icon,logo,ext} from './ui/icons.js';import {routeName,advance,clamp,elapsedFrameTime} from './core.js';import {hydrateProfile} from './ui/profile.js';
const main=document.querySelector('#main'),header=document.querySelector('#header'),footer=document.querySelector('#footer');
let scene=null,cardOptics=null,route='',generation=0;let stored={};try{stored=JSON.parse(localStorage.getItem('dxt-settings')||'{}');}catch{}
const settings={quality:['auto','low','high'].includes(stored.quality)?stored.quality:'auto',paused:!!stored.paused};const save=()=>{try{localStorage.setItem('dxt-settings',JSON.stringify(settings));}catch{}};
function shell(){header.innerHTML=`<a href="/" data-route class="brand" aria-label="DXT home">${logo('dxt')}</a><nav class="navigation" id="navigation" aria-label="Main navigation">${nav.map(([key,title])=>`<a href="${key==='home'?'/':'/'+key}" data-route ${key===route?'aria-current="page"':''}>${title}</a>`).join('')}</nav><div class="header-right"><span class="header-motto">BUILD / DRIVE / CREATE / BEYOND</span><div class="toolbar"><button id="quality" class="tool quality-tool" aria-label="Rendering quality: ${settings.quality}">${icon('quality')}<span>${settings.quality}</span></button><button id="pause" class="tool" aria-label="${settings.paused?'Resume':'Pause'} animated effects" aria-pressed="${settings.paused}">${icon(settings.paused?'play':'pause')}</button></div><div class="header-socials"><a href="${CONTENT.links.youtube}" target="_blank" rel="noopener noreferrer" aria-label="youtube">${icon('youtube')}</a><a href="${CONTENT.links.instagram}" target="_blank" rel="noopener noreferrer" aria-label="instagram">${icon('instagram')}</a><a href="${CONTENT.links.discord}" target="_blank" rel="noopener noreferrer" aria-label="discord">${icon('discord')}</a></div><button class="menu-toggle" aria-controls="navigation" aria-expanded="false" aria-label="Open navigation">${icon('menu')}</button></div>`;
 footer.innerHTML=`<a href="/" data-route class="footer-brand" aria-label="Home">${logo('dxt')}</a><span>DXT / A PERSONAL SPACE FOR GAMES, PEOPLE AND IDEAS.</span><div class="footer-right"><a href="/contact" data-route>GET IN TOUCH ${icon('external')}</a><span>DXRKTHS.VERCEL.APP</span></div>`;
 header.querySelector('#quality').onclick=()=>{const names=['auto','low','high'];settings.quality=names[(names.indexOf(settings.quality)+1)%names.length];save();scene?.setSettings();if(cardOptics){cardOptics.dirty=true;cardOptics.wake();}shell();};
 header.querySelector('#pause').onclick=()=>{settings.paused=!settings.paused;save();scene?.setSettings();if(cardOptics){cardOptics.dirty=true;cardOptics.wake();}shell();};
 header.querySelector('.menu-toggle').onclick=()=>{const nav=header.querySelector('nav'),button=header.querySelector('.menu-toggle'),open=nav.classList.toggle('open');button.setAttribute('aria-expanded',String(open));button.setAttribute('aria-label',(open?'Close':'Open')+' navigation');};
}
async function render(path,focus=false){const token=++generation;scene?.dispose();cardOptics?.dispose();scene=null;cardOptics=null;route=routeName(path);document.body.dataset.page=route;main.innerHTML=pages[route]();main.classList.remove('page-enter');void main.offsetWidth;main.classList.add('page-enter');shell();document.title=route==='home'?'DXT | Berserk Drift X':`${nav.find(([k])=>k===route)?.[1]||'Off the track'} | DXT`;document.querySelector('#announcer').textContent=document.title;
 if(focus){window.scrollTo({top:0,behavior:'instant'});main.focus({preventScroll:true});}hydrateProfile(main);if(route==='home')cardOptics=new PerspectiveCards(main.querySelector('.reference-home'),settings);
 try{if(route==='home'){const {HeroScene}=await import('./render/showroom.bundle.js');if(token===generation)scene=new HeroScene(document.querySelector('#hero-canvas'),settings);}else if(route==='about'){const {LogoScene}=await import('./render/logo.js');if(token===generation)scene=new LogoScene(document.querySelector('#logo-canvas'),settings);}}catch(e){console.warn('[DXT] Optical layer unavailable:',e.message);}
}
document.addEventListener('click',e=>{const a=e.target.closest('a[data-route]');if(!a||e.button!==0||e.ctrlKey||e.metaKey||e.shiftKey||e.altKey)return;const u=new URL(a.href);if(u.origin!==location.origin)return;e.preventDefault();if(u.pathname!==location.pathname){history.pushState({},'',u.pathname);render(u.pathname,true);}else{header.querySelector('nav')?.classList.remove('open');header.querySelector('.menu-toggle')?.setAttribute('aria-expanded','false');window.scrollTo({top:0,behavior:'smooth'});}});
window.addEventListener('popstate',()=>render(location.pathname,true));document.addEventListener('keydown',e=>{if(e.key==='Escape'){header.querySelector('nav')?.classList.remove('open');header.querySelector('.menu-toggle')?.setAttribute('aria-expanded','false');}});
// Pointer response is interpolated rather than changing brightness on :hover alone.
let materialRAF=0;const materials=new Map();function animateMaterials(now){materialRAF=0;let active=false;for(const [el,s]of materials){if(!el.isConnected){materials.delete(el);continue;}const dt=elapsedFrameTime(now,s.last);s.last=now;s.light=advance(s.light,s.goal,9,dt);s.x=advance(s.x,s.tx,13,dt);s.y=advance(s.y,s.ty,13,dt);el.style.setProperty('--mx',s.x+'px');el.style.setProperty('--my',s.y+'px');el.style.setProperty('--glow',s.light);if(Math.abs(s.light-s.goal)>.002||Math.abs(s.x-s.tx)>.1||Math.abs(s.y-s.ty)>.1)active=true;else if(s.goal===0)materials.delete(el);}if(active)materialRAF=requestAnimationFrame(animateMaterials);}
function light(e,goal){const el=e.target.closest('.material');if(!el)return;const rect=el.getBoundingClientRect(),s=materials.get(el)||{x:rect.width/2,y:rect.height/2,light:0,last:performance.now()};s.tx=e.clientX!=null?clamp(e.clientX-rect.left,0,rect.width):rect.width/2;s.ty=e.clientY!=null?clamp(e.clientY-rect.top,0,rect.height):rect.height/2;s.goal=goal;materials.set(el,s);if(!materialRAF){s.last=performance.now();materialRAF=requestAnimationFrame(animateMaterials);}}
document.addEventListener('pointermove',e=>light(e,1),{passive:true});document.addEventListener('pointerout',e=>{const el=e.target.closest('.material');if(el&&!el.contains(e.relatedTarget))light(e,0);},{passive:true});document.addEventListener('focusin',e=>light(e,.7));document.addEventListener('focusout',e=>light(e,0));
window.addEventListener('pagehide',e=>{if(!e.persisted)scene?.dispose();else scene?.sleep();cardOptics?.sleep();cancelAnimationFrame(materialRAF);materialRAF=0;});window.addEventListener('pageshow',()=>scene?.wake());
render(location.pathname);if(new URLSearchParams(location.search).has('debug'))window.__DXT__={inspect:()=>({route,settings:{...settings},scene:scene?.inspect()??null,materials:materials.size,cards:cardOptics?.inspect()??null}),scene:()=>scene,cards:()=>cardOptics};
