import {Program,mesh,bind,imageTexture,loadImage} from './gl.js';
import {Motion,slotY,chainOffset,damp,random,clamp,viewMatrix} from './core.js';
import {CONTENT} from './content.js';
import {multiply,invert,unproject,project,mat4,perspective,translation} from './math.js';
import {buildScene} from './world/scene.js';
import {combine,model,panel,tube} from './world/geometry.js';
import {buildChains,sampleChainPose,CHAIN_COUNT,ChainInstances} from './world/chains.js';
import {Dynamics,History} from './world/dynamics.js';
import {canonicalCamera,cardModel,reflectionMatrix,reflectPoint,FLOOR} from './render/camera.js';
import {distortUv,undistortUv} from './render/lens.js';
import {buildLightRig,updateLightRig} from './render/lighting.js';
import {qualityProfile,QualityGovernor} from './render/quality.js';
import {cardLifecycle,galleryInstances,cardCoverage} from './render/card-lifecycle.js';
import {TargetPool,copyColor} from './render/targets.js';
import {probeCapabilities} from './render/capabilities.js';
import {ShaderLibrary} from './render/shader-library.js';
import {RenderGraph} from './render/graph.js';
import {VERSION} from './render/contracts.js';
const ID=mat4();
const PROGRAMS={stone:['common/world.vert','pbr/surface.frag'],prepass:['common/world.vert','pbr/prepass.frag'],ao:['common/full.vert','pbr/ao.frag'],vista:['common/world.vert','pbr/vista.frag'],shadow:['common/world.vert','shadow/depth.frag'],floor:['common/world.vert','reflection/floor.frag'],cardDepth:['common/world.vert','glass/depth.frag'],card:['common/world.vert','glass/crystal.frag'],media:['common/world.vert','glass/media.frag'],flame:['common/world.vert','fire/flame.frag'],lava:['common/world.vert','fire/lava.frag'],background:['common/full.vert','atmosphere/sky.frag'],volume:['common/full.vert','atmosphere/volume.frag'],composite:['common/full.vert','atmosphere/composite.frag'],art:['common/full.vert','glass/art.frag'],particles:['particles/sparks.vert','particles/sparks.frag'],resolve:['common/full.vert','optics/resolve.frag'],blur:['common/full.vert','optics/blur.frag'],visibility:['common/full.vert','optics/visibility.frag'],output:['common/full.vert','optics/output.frag']};
/** Stable interaction facade. Scene geometry, illumination and optics share one world. */
export class Forge{
 constructor(canvas){
  this.canvas=canvas;this.gl=canvas.getContext('webgl2',{alpha:false,antialias:false,powerPreference:'high-performance'});if(!this.gl)throw Error('WebGL2 indisponível');
  this.capabilities=probeCapabilities(this.gl);this.hdr=this.capabilities.floatColor;this.artHdr=this.hdr;
  this.reference=new URLSearchParams(location.search).has('reference');this.ready=false;this.time=this.reference?3:0;this.previousTime=0;this.delta=1/60;this.motion=new Motion(CONTENT.projects.length);this.pointer=[0,0];this.pointerTarget=[0,0];this.hover=-1;this.frames=0;this.drawCalls=0;this.paused=this.reference;this.reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;this.quality='auto';this.contextLost=false;
  this.dynamics=new Dynamics();this.history=new History();this.graph=new RenderGraph();this.governor=new QualityGovernor();this.pressure=0;
  const reset=this.motion.reset.bind(this.motion);this.motion.reset=()=>{reset();this.dynamics.reset();this.occurrences?.clear();this.clear();this.invalidateHistory('Home');};
  this.previousTravel=0;this.previousVP=ID;this.programs={};this.meshes={};this.targets=[];this.frozenQuality=new URLSearchParams(location.search).has('reference');this.effects={bloom:true,flare:true,motion:true,heat:true,volume:true,shadows:true,reflection:true};
  this.pool=new TargetPool(this.gl);this.mediaPool=new TargetPool(this.gl);this.makeWorld();this.lights=buildLightRig();this.lightState=updateLightRig(this.lights,0);
  this.occurrences=new Map();this.renderCards=[];this.hoverKey=null;
  this.cards=CONTENT.projects.map((content,index)=>({index,content,hover:0,pointer:[.5,.5],trails:Array(24).fill(0),trailSlot:0,lastTrail:-1,label:null,tex:null,model:ID,previousModel:ID,inverse:null,rawY:null,visualY:null,visible:true}));
 }
 makeWorld(){this.world=buildScene();this.objects=this.world.objects;this.fires=this.world.fires;this.chainCount=CHAIN_COUNT;this.chains=buildChains();}
 linkPose(link,position){return sampleChainPose(link,position);}
 model(pos,rot,scale){return model(pos,rot,scale);}
 async initialize(){
  const g=this.gl,library=new ShaderLibrary(),sources=await Promise.all(Object.entries(PROGRAMS).map(async([name,paths])=>[name,...await library.pair(...paths)]));
  for(const[name,vs,fs]of sources){try{this.programs[name]=new Program(g,vs,fs);}catch(e){throw Error(name+': '+e.message);}}
  for(const[name,geometry]of Object.entries(this.world.geometry))this.meshes[name]=mesh(g,geometry);
  this.meshes.world=mesh(g,combine(this.objects,this.world.geometry));this.meshes.plane=mesh(g,panel(2,2));this.meshes.panel=this.meshes.glass;this.meshes.media=mesh(g,panel());this.meshes.chain=mesh(g,tube('chain'));
  this.instances=new ChainInstances(g,this.meshes.chain,this.chains.length);this.makeSparks();this.makeProbe();
  for(const c of this.cards){c.label=this.makeLabel(c.content,c.index);const rt=this.mediaPool.color('demo-'+c.index,1440,594,{hdr:this.artHdr});this.setTarget(rt);g.disable(g.DEPTH_TEST);g.disable(g.BLEND);this.programs.art.use({uIndex:c.index});this.full();c.demoTarget=rt;c.tex=rt.t;c.mediaAspect=1440/594;
   if(c.content.kind==='image'&&c.content.src){try{const im=new Image();im.crossOrigin='anonymous';im.src=c.content.src;await im.decode();c.tex=imageTexture(g,im);c.mediaAspect=im.naturalWidth/im.naturalHeight;}catch{c.mediaError=true;}}
   if(c.content.kind==='video'){
    if(c.content.poster){try{const im=new Image();im.crossOrigin='anonymous';im.src=c.content.poster;await im.decode();c.tex=imageTexture(g,im);c.mediaAspect=im.naturalWidth/im.naturalHeight;}catch{c.mediaError=true;}}
    if(c.content.src){const v=document.createElement('video');v.muted=true;v.loop=true;v.playsInline=true;v.crossOrigin='anonymous';v.preload='none';v.src=c.content.src;c.video=v;c.videoPlaying=false;}
   }
  }
  try{this.vistaTexture=await loadImage(g,'assets/world/far-vista-right.webp');this.makeVista();}catch(e){this.vistaTexture=null;console.warn('[BRAAZA] Distant vista unavailable: '+e.message);}
  this.resize();this.update(0);this.renderShadows();this.captureProbe();this.render();this.ready=true;
 }
 makeVista(){const cam=canonicalCamera(1672,941,[0,0]),bounds=[1288/1672,126/941,1450/1672,380/941],points=[];for(const uv of[[bounds[0],bounds[3]],[bounds[2],bounds[3]],[bounds[2],bounds[1]],[bounds[0],bounds[1]]]){const q=undistortUv(uv,cam.lens),a=unproject(cam.inverseViewProjection,q[0]*2-1,1-q[1]*2,-1),b=unproject(cam.inverseViewProjection,q[0]*2-1,1-q[1]*2,1),t=(-65-a[2])/(b[2]-a[2]);points.push(...a.map((v,i)=>v+(b[i]-v)*t));}this.meshes.vista=mesh(this.gl,{positions:points,normals:[0,0,1,0,0,1,0,0,1,0,0,1],uvs:[0,0,1,0,1,1,0,1],indices:[0,1,2,0,2,3]});}
 drawVista(vp=this.vp){if(!this.vistaTexture)return;const g=this.gl;g.enable(g.DEPTH_TEST);g.depthMask(true);g.enable(g.BLEND);g.blendFunc(g.SRC_ALPHA,g.ONE_MINUS_SRC_ALPHA);g.disable(g.CULL_FACE);bind(g,this.vistaTexture,0);this.programs.vista.use({...this.base(vp),uMap:0,uTime:this.time});this.draw(this.meshes.vista);g.disable(g.BLEND);g.enable(g.CULL_FACE);}
 makeLabel(content,index){const cv=document.createElement('canvas');cv.width=1075;cv.height=575;const ctx=cv.getContext('2d'),bg=ctx.createLinearGradient(0,300,0,575);bg.addColorStop(0,'rgba(0,0,0,0)');bg.addColorStop(1,'rgba(0,0,0,.83)');ctx.fillStyle=bg;ctx.fillRect(0,0,1075,575);ctx.fillStyle='#e9e5df';ctx.font='25px monospace';ctx.fillText(content.title,53,478);ctx.fillStyle='#bcb0a3';ctx.font='13px monospace';ctx.fillText(content.kind==='demo'?'PRÉVIA / DEMONSTRAÇÃO':content.kind==='video'?'VÍDEO / REPRODUZIR':'IMAGEM / EXPLORAR',53,516);ctx.fillStyle='#f2dec5';ctx.font='20px monospace';ctx.fillText(String(index+1).padStart(2,'0'),990,519);return imageTexture(this.gl,cv);}
 makeSparks(){const g=this.gl,r=random(722),a=[];this.sparkCount=900;for(let i=0;i<this.sparkCount;i++){const spread=r()>.64?13:5.6;a.push((r()-.5)*spread,r(),r());}this.sparkVao=g.createVertexArray();this.sparkBuffer=g.createBuffer();g.bindVertexArray(this.sparkVao);g.bindBuffer(g.ARRAY_BUFFER,this.sparkBuffer);g.bufferData(g.ARRAY_BUFFER,new Float32Array(a),g.STATIC_DRAW);g.enableVertexAttribArray(0);g.vertexAttribPointer(0,3,g.FLOAT,false,0,0);g.bindVertexArray(null);}
 makeProbe(){const g=this.gl;this.probeSize=128;this.probe=g.createTexture();this.emptyProbe=g.createTexture();for(const tex of[this.emptyProbe,this.probe]){g.bindTexture(g.TEXTURE_CUBE_MAP,tex);const size=tex===this.probe?this.probeSize:1;for(let face=0;face<6;face++)g.texImage2D(g.TEXTURE_CUBE_MAP_POSITIVE_X+face,0,this.hdr?g.RGBA16F:g.RGBA8,size,size,0,g.RGBA,this.hdr?g.HALF_FLOAT:g.UNSIGNED_BYTE,null);g.texParameteri(g.TEXTURE_CUBE_MAP,g.TEXTURE_MIN_FILTER,g.LINEAR_MIPMAP_LINEAR);g.texParameteri(g.TEXTURE_CUBE_MAP,g.TEXTURE_MAG_FILTER,g.LINEAR);for(const k of[g.TEXTURE_WRAP_S,g.TEXTURE_WRAP_T,g.TEXTURE_WRAP_R])g.texParameteri(g.TEXTURE_CUBE_MAP,k,g.CLAMP_TO_EDGE);g.generateMipmap(g.TEXTURE_CUBE_MAP);}this.probeFbo=g.createFramebuffer();this.probeDepth=g.createRenderbuffer();g.bindRenderbuffer(g.RENDERBUFFER,this.probeDepth);g.renderbufferStorage(g.RENDERBUFFER,g.DEPTH_COMPONENT24,this.probeSize,this.probeSize);this.probeReady=false;}
 resize(){if(!this.programs.stone)return;const g=this.gl;this.width=innerWidth;this.height=innerHeight;this.mobile=this.width<this.height*.88;this.profile=qualityProfile(this.quality,this.mobile,devicePixelRatio||1,this.pressure);if(!this.hdr)this.profile.motion=false;
  const fixed=this.profile.shadow**2*8+4*1440*594*8+128**2*6*8*1.34;this.dpr=Math.min(this.profile.scale,Math.sqrt(Math.max(1,this.profile.memoryBudget-fixed)/(this.width*this.height*87)));const w=Math.max(4,Math.round(this.width*this.dpr)),h=Math.max(4,Math.round(this.height*this.dpr));this.canvas.width=w;this.canvas.height=h;
  this.pool.dispose();const add=(id,x=w,y=h,options={})=>this.pool.color(id,x,y,{hdr:this.hdr,...options});
  this.sceneTarget=add('scene',w,h,{depth:true});this.normalTarget=add('normal',w,h,{hdr:false,nearest:true});this.velocityTarget=add('velocity',w,h,{nearest:true});
  g.bindFramebuffer(g.FRAMEBUFFER,this.sceneTarget.f);g.framebufferTexture2D(g.FRAMEBUFFER,g.COLOR_ATTACHMENT1,g.TEXTURE_2D,this.normalTarget.t,0);g.framebufferTexture2D(g.FRAMEBUFFER,g.COLOR_ATTACHMENT2,g.TEXTURE_2D,this.velocityTarget.t,0);g.drawBuffers([g.COLOR_ATTACHMENT0,g.COLOR_ATTACHMENT1,g.COLOR_ATTACHMENT2]);if(g.checkFramebufferStatus(g.FRAMEBUFFER)!==g.FRAMEBUFFER_COMPLETE)throw Error('MRT framebuffer incomplete');
  this.behindTarget=add('transmission-environment');this.internalTarget=add('transmission-with-media');this.resolvedTarget=add('optical-resolve');this.fireTarget=add('fire',w,h,{sharedDepth:this.sceneTarget.depth});this.particleTarget=add('particles',w,h,{sharedDepth:this.sceneTarget.depth});this.reflectTarget=add('planar-reflection',w*this.profile.reflection,h*this.profile.reflection,{depth:true});this.volumeTarget=add('volume',w*this.profile.volume,h*this.profile.volume);this.aoTarget=add('ambient-occlusion',w*.5,h*.5,{hdr:false});
  g.bindFramebuffer(g.FRAMEBUFFER,this.normalTarget.f);g.framebufferTexture2D(g.FRAMEBUFFER,g.COLOR_ATTACHMENT1,g.TEXTURE_2D,this.velocityTarget.t,0);g.framebufferTexture2D(g.FRAMEBUFFER,g.DEPTH_ATTACHMENT,g.TEXTURE_2D,this.sceneTarget.depth,0);g.drawBuffers([g.COLOR_ATTACHMENT0,g.COLOR_ATTACHMENT1]);
  this.opaqueDepth=this.pool.depth('opaque-depth',w,h);this.shadows=[0,1].map(i=>this.pool.depth('shadow-'+i,this.profile.shadow));this.blooms=[0,1,2,3,4].map((_,i)=>[add('bloom-'+i+'-x',Math.ceil(w/2**(i+1)),Math.ceil(h/2**(i+1))),add('bloom-'+i+'-y',Math.ceil(w/2**(i+1)),Math.ceil(h/2**(i+1)))]);this.visibilities=[0,1].map(i=>add('flare-'+i,2,1,{hdr:false}));for(const t of this.visibilities){this.setTarget(t);g.clearColor(0,0,0,1);g.clear(g.COLOR_BUFFER_BIT);}this.visibilityIndex=0;this.targets=this.pool.items;this.invalidateHistory('resize/quality');this.update(0);
 }
 invalidateHistory(reason){this.history?.invalidate(reason);this.graph?.invalidateHistory(reason);}
 setTarget(t){const g=this.gl;g.bindFramebuffer(g.FRAMEBUFFER,t?.f??null);g.viewport(0,0,t?.w??this.canvas.width,t?.h??this.canvas.height);}
 full(){const g=this.gl;g.bindVertexArray(null);g.drawArrays(g.TRIANGLES,0,3);this.drawCalls++;}
 draw(m){const g=this.gl;g.bindVertexArray(m.vao);g.drawElements(g.TRIANGLES,m.count,g.UNSIGNED_INT,0);this.drawCalls++;}
 update(dt){this.delta=dt||this.delta;this.motion.step(dt,this.reduced);if(!this.paused&&!this.reduced){this.time+=dt;this.dynamics.step(dt,this.motion.velocity*.09);}for(let i=0;i<2;i++)this.pointer[i]=this.reduced?this.pointerTarget[i]:damp(this.pointer[i],this.pointerTarget[i],4,dt);this.cameraState=canonicalCamera(this.width||innerWidth,this.height||innerHeight,this.pointer);this.camera=this.cameraState.position;this.vp=this.cameraState.viewProjection;this.historyValid=this.history.accept(this.motion.travel)&&!this.reduced&&!this.paused;this.lightState=updateLightRig(this.lights,this.time);
  for(const c of this.cards){if(c.video){const play=this.hover===c.index&&!this.paused&&!this.reduced;if(play&&!c.videoPlaying){c.videoPlaying=true;c.video.play().catch(()=>{c.mediaError=true;});}else if(!play&&c.videoPlaying){c.video.pause();c.videoPlaying=false;}}}
  const next=new Map();
  for(const sample of galleryInstances(this.motion.travel,this.cards.length)){
   const source=this.cards[sample.index],c=this.occurrences.get(sample.key)??{source,index:sample.index,key:sample.key,hover:0,model:ID,previousModel:ID};
   c.y=sample.y;c.visible=sample.visible;
   c.hover=damp(c.hover,c.key===this.hoverKey?1:0,8,dt);
   c.model=cardModel(c.y,this.cameraState,c.hover,source.pointer);c.inverse=invert(multiply(this.vp,c.model));
   const screen=project(multiply(this.vp,c.model),[0,0,0]),uv=distortUv([screen[0]*.5+.5,.5-screen[1]*.5],this.cameraState.lens);
   c.screen=[uv[0]*2-1,1-uv[1]*2,screen[2]];next.set(c.key,c);
  }
  this.occurrences=next;this.renderCards=[...next.values()];
  // Preserve the public content array: it owns each texture/video exactly once.
  for(const source of this.cards){const matches=this.renderCards.filter(c=>c.index===source.index),c=matches.reduce((a,b)=>Math.abs(a.y-5.1)<Math.abs(b.y-5.1)?a:b);Object.assign(source,{y:c.y,visualY:c.y,rawY:c.y,model:c.model,inverse:c.inverse,screen:c.screen,hover:c.hover});}
  this.lightVPs=this.lights.slice(0,2).map(l=>multiply(perspective(2.2,1,.12,75),viewMatrix(l.position,l.target)));this.reflectVP=multiply(this.vp,reflectionMatrix());this.instances?.update(this.chains,this.motion.travel,this.previousTravel,this.historyValid,this.dynamics.value);
 }
 point(x,y,time){this.pointerTarget=[x*2-1,1-y*2];const hit=this.pick(x,y);this.hover=hit?.index??-1;this.hoverKey=hit?.key??null;if(hit){const c=this.cards[hit.index];c.pointer=hit.uv;if(!this.reduced&&time-c.lastTrail>.04){c.lastTrail=time;const slot=(c.trailSlot++%6)*4;c.trails.splice(slot,4,...hit.uv,this.time,.65);}}return hit;}
 clear(){this.hover=-1;this.hoverKey=null;this.pointerTarget=[0,0];}
 pick(x,y){if(!this.cameraState)return null;const uv=undistortUv([x,y],this.cameraState.lens);let nearest=null;for(const c of this.renderCards){if(!c.inverse||!c.visible)continue;const a=unproject(c.inverse,uv[0]*2-1,1-uv[1]*2,-1),b=unproject(c.inverse,uv[0]*2-1,1-uv[1]*2,1),dz=b[2]-a[2];if(Math.abs(dz)<1e-8)continue;const t=-a[2]/dz;if(t<0||t>1)continue;const px=a[0]+(b[0]-a[0])*t,py=a[1]+(b[1]-a[1])*t;if(Math.abs(px)<2.38&&Math.abs(py)<1.10&&cardCoverage(c.y,[px,py],c.index)>=.55&&(!nearest||c.screen[2]<nearest.depth))nearest={index:c.index,key:c.key,uv:[px/4.8+.5,py/2.25+.5],depth:c.screen[2]};}return nearest;}
 base(vp=this.vp,camera=this.camera,reflection=false){return {uVP:vp,uPreviousVP:this.historyValid?this.previousVP:vp,uModel:ID,uPreviousModel:ID,uTime:this.time,uPreviousTime:this.historyValid?this.previousTime:this.time,uHistory:+this.historyValid,uSurface:[0,.05,0,1],uInstanced:0,uVertexSurface:0,uCloth:0,uCamera:camera,uLightPos:this.lightState.positions,uLightColor:this.lightState.colors,uLightVP0:this.lightVPs[0],uLightVP1:this.lightVPs[1],uShadow0:6,uShadow1:7,uShadowTexel:1/this.profile.shadow,uShadows:+this.effects.shadows,uUseProbe:+this.probeReady,uProbe:8,uReflection:+reflection,uScreenAO:10,uAOResolution:[this.canvas.width,this.canvas.height],uUseAO:+(this.aoReady&&!reflection&&vp===this.vp)};}
 lightTextures(useProbe=true){const g=this.gl;bind(g,this.shadows[0].t,6);bind(g,this.shadows[1].t,7);g.activeTexture(g.TEXTURE0+8);g.bindTexture(g.TEXTURE_CUBE_MAP,useProbe?this.probe:this.emptyProbe);if(this.aoTarget)bind(g,this.aoTarget.t,10);}
 drawGeometry(program,base){program.use({...base,uVertexSurface:1,uInstanced:0,uModel:ID,uPreviousModel:ID,uCloth:0});this.draw(this.meshes.world);program.use({uVertexSurface:0,uInstanced:1});this.instances.draw();this.drawCalls++;program.use({uInstanced:0});for(const o of this.world.floaters){const bob=Math.sin(this.time*.3+o.seed)*.055,prevBob=Math.sin(this.previousTime*.3+o.seed)*.055,m=model([o.pos[0],o.pos[1]+bob,o.pos[2]],[.2,o.seed+this.time*.018,.4],o.scale),previous=model([o.pos[0],o.pos[1]+prevBob,o.pos[2]],[.2,o.seed+this.previousTime*.018,.4],o.scale);program.use({uModel:m,uPreviousModel:previous,uSurface:o.surface});this.draw(this.meshes[o.mesh]);}for(const b of this.world.banners){program.use({uModel:b.model,uPreviousModel:b.model,uCloth:1,uSurface:[4,0,b.seed,1]});this.draw(this.meshes.banner);}program.use({uCloth:0});}
 renderShadows(){const g=this.gl;this.graph.mark('shadow');g.disable(g.BLEND);g.enable(g.DEPTH_TEST);g.depthMask(true);g.enable(g.CULL_FACE);g.cullFace(g.BACK);g.frontFace(g.CCW);g.enable(g.POLYGON_OFFSET_FILL);g.polygonOffset(1.1,1.5);for(let i=0;i<2;i++){this.setTarget(this.shadows[i]);g.clearDepth(1);g.clear(g.DEPTH_BUFFER_BIT);this.drawGeometry(this.programs.shadow,{...this.base(this.lightVPs[i]),uVP:this.lightVPs[i],uHistory:0});}g.disable(g.POLYGON_OFFSET_FILL);}
 sky(target){const g=this.gl;g.disable(g.BLEND);g.disable(g.DEPTH_TEST);g.disable(g.CULL_FACE);this.programs.background.use({uResolution:[target.w,target.h],uTime:this.time,uPointer:this.pointer});this.full();g.enable(g.DEPTH_TEST);g.depthMask(true);g.depthFunc(g.LEQUAL);g.enable(g.CULL_FACE);}
 drawFire(vp,reflection=false){const g=this.gl;g.disable(g.CULL_FACE);g.enable(g.BLEND);g.blendFunc(g.ONE,g.ONE_MINUS_SRC_ALPHA);g.depthMask(false);const lava=this.programs.lava;lava.use({...this.base(vp,this.camera,reflection),uFall:0,uSeed:0});for(const[y,z]of[[.48,-.9],[13.02,-1.6]]){lava.use({uModel:model([0,y,z],[-Math.PI/2,0,0],[y>10?1.45:2.25,y>10?1.45:2.25,1])});this.draw(this.meshes.plane);}lava.use({uFall:1});for(const f of this.world.lavafalls){lava.use({uModel:model(f.pos,f.rot,f.scale),uSeed:f.seed});this.draw(this.meshes.plane);}const fp=this.programs.flame;fp.use(this.base(vp,this.camera,reflection));for(const f of[...this.fires].sort((a,b)=>a.pos[2]-b.pos[2])){fp.use({uModel:model(f.pos,f.rot,f.scale),uSeed:f.seed,uOpacity:f.opacity});this.draw(this.meshes.plane);}g.depthMask(true);g.disable(g.BLEND);}
 updateMedia(){
  const g=this.gl;for(const c of this.cards){if(!c.video||c.video.readyState<2||!c.videoPlaying)continue;if(!c.videoTex)c.videoTex=imageTexture(g,c.video);else{bind(g,c.videoTex,0);g.pixelStorei(g.UNPACK_FLIP_Y_WEBGL,true);g.texImage2D(g.TEXTURE_2D,0,g.SRGB8_ALPHA8,g.RGBA,g.UNSIGNED_BYTE,c.video);g.generateMipmap(g.TEXTURE_2D);}c.tex=c.videoTex;c.mediaAspect=c.video.videoWidth/c.video.videoHeight;}
 }
 drawCards(vp,reflection=false,mediaOnly=false){
  const g=this.gl,p=mediaOnly?this.programs.media:this.programs.card;
  g.enable(g.DEPTH_TEST);g.depthFunc(g.LEQUAL);g.depthMask(false);g.enable(g.BLEND);g.blendFunc(g.SRC_ALPHA,g.ONE_MINUS_SRC_ALPHA);g.enable(g.CULL_FACE);g.cullFace(g.BACK);
  const w=reflection?this.reflectTarget.w:this.canvas.width,h=reflection?this.reflectTarget.h:this.canvas.height;
  p.use({...this.base(vp,reflection?reflectPoint(this.camera):this.camera,reflection),uArt:0,uLabel:1,uBehind:2,uResolution:[w,h],uHasInternalScene:+(!reflection&&!mediaOnly)});
  for(const c of this.renderCards.filter(c=>c.visible).sort((a,b)=>b.y-a.y)){
   const source=c.source;bind(g,source.tex,0);bind(g,source.label,1);
   const previous=this.historyValid&&Math.abs(c.y-(c.previousY??Infinity))<1?c.previousModel:c.model;
   p.use({uModel:mediaOnly?multiply(c.model,translation(0,0,-.17)):c.model,uPreviousModel:previous,uPointer:source.pointer,uHover:c.hover,uTrail:source.trails,uCardY:c.y,uIndex:c.index,uMediaAspect:source.mediaAspect});this.draw(mediaOnly?this.meshes.media:this.meshes.panel);
  }
  g.disable(g.BLEND);g.depthMask(true);
 }
 drawCardDepth(){
  const g=this.gl,p=this.programs.cardDepth;g.enable(g.DEPTH_TEST);g.depthMask(true);g.disable(g.BLEND);g.colorMask(false,false,false,false);p.use(this.base());
  for(const c of this.renderCards){if(!c.visible)continue;p.use({uModel:c.model,uCardY:c.y,uIndex:c.index});this.draw(this.meshes.panel);}
  g.colorMask(true,true,true,true);
 }
 renderReflection(){const g=this.gl;this.graph.mark('reflection');this.setTarget(this.reflectTarget);g.clearColor(.005,.005,.007,1);g.clearDepth(1);g.clear(g.COLOR_BUFFER_BIT|g.DEPTH_BUFFER_BIT);this.sky(this.reflectTarget);g.frontFace(g.CW);this.lightTextures();this.drawGeometry(this.programs.stone,this.base(this.reflectVP,reflectPoint(this.camera),true));this.drawFire(this.reflectVP,true);bind(g,this.behindTarget.t,2);this.drawCards(this.reflectVP,true,false);g.frontFace(g.CCW);}
 captureProbe(){const g=this.gl,size=this.probeSize,eye=[0,5,0],directions=[[1,0,0],[-1,0,0],[0,1,0],[0,-1,0],[0,0,1],[0,0,-1]],ups=[[0,-1,0],[0,-1,0],[0,0,1],[0,0,-1],[0,-1,0],[0,-1,0]];const look=(target,up)=>{const norm=a=>{const l=Math.hypot(...a);return a.map(v=>v/l);},cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]],z=norm(target.map(v=>-v)),x=norm(cross(up,z)),y=cross(z,x),dot=a=>a.reduce((s,v,i)=>s+v*eye[i],0);return new Float32Array([x[0],y[0],z[0],0,x[1],y[1],z[1],0,x[2],y[2],z[2],0,-dot(x),-dot(y),-dot(z),1]);};this.lightTextures(false);
  for(let face=0;face<6;face++){g.bindFramebuffer(g.FRAMEBUFFER,this.probeFbo);g.framebufferTexture2D(g.FRAMEBUFFER,g.COLOR_ATTACHMENT0,g.TEXTURE_CUBE_MAP_POSITIVE_X+face,this.probe,0);g.framebufferRenderbuffer(g.FRAMEBUFFER,g.DEPTH_ATTACHMENT,g.RENDERBUFFER,this.probeDepth);g.viewport(0,0,size,size);g.clearColor(.006,.006,.008,1);g.clear(g.COLOR_BUFFER_BIT|g.DEPTH_BUFFER_BIT);const vp=multiply(perspective(Math.PI/2,1,.1,140),look(directions[face],ups[face]));this.sky({w:size,h:size});g.frontFace(g.CCW);this.drawGeometry(this.programs.stone,{...this.base(vp,eye),uUseProbe:0,uUseAO:0});this.drawFire(vp);}g.bindFramebuffer(g.FRAMEBUFFER,null);g.activeTexture(g.TEXTURE0+8);g.bindTexture(g.TEXTURE_CUBE_MAP,this.probe);g.generateMipmap(g.TEXTURE_CUBE_MAP);this.probeReady=true;
 }
 renderAmbientOcclusion(){const g=this.gl;this.graph.mark('geometry-prepass');this.aoReady=false;this.setTarget(this.normalTarget);g.drawBuffers([g.COLOR_ATTACHMENT0,g.COLOR_ATTACHMENT1]);g.clearBufferfv(g.COLOR,0,new Float32Array([.5,.5,1,0]));g.clearBufferfv(g.COLOR,1,new Float32Array([0,0,0,0]));g.clearDepth(1);g.depthMask(true);g.clear(g.DEPTH_BUFFER_BIT);g.enable(g.DEPTH_TEST);g.depthFunc(g.LEQUAL);g.disable(g.BLEND);g.enable(g.CULL_FACE);g.frontFace(g.CCW);this.drawGeometry(this.programs.prepass,this.base());const floorModel=model([0,FLOOR,-12],[-Math.PI/2,0,0],[65,65,1]);this.programs.prepass.use({...this.base(),uModel:floorModel,uPreviousModel:floorModel});this.draw(this.meshes.plane);this.graph.mark('ambient-occlusion');this.setTarget(this.aoTarget);g.disable(g.DEPTH_TEST);g.disable(g.CULL_FACE);bind(g,this.sceneTarget.depth,0);bind(g,this.normalTarget.t,1);this.programs.ao.use({uDepth:0,uNormal:1,uInverseVP:this.cameraState.inverseViewProjection,uVP:this.vp,uSamples:this.profile.low?4:8});this.full();this.aoReady=true;}
 render(){if(this.contextLost||!this.sceneTarget)return;const started=performance.now(),g=this.gl;this.drawCalls=0;this.graph.begin();this.updateMedia();this.renderShadows();if(this.effects.reflection)this.renderReflection();this.renderAmbientOcclusion();
  this.graph.mark('opaque');this.setTarget(this.sceneTarget);g.drawBuffers([g.COLOR_ATTACHMENT0,g.COLOR_ATTACHMENT1,g.COLOR_ATTACHMENT2]);g.clearBufferfv(g.COLOR,0,new Float32Array([0,0,0,1]));g.clearBufferfv(g.COLOR,1,new Float32Array([.5,.5,1,0]));g.clearBufferfv(g.COLOR,2,new Float32Array([0,0,0,0]));g.drawBuffers([g.COLOR_ATTACHMENT0]);this.sky(this.sceneTarget);this.drawVista();g.drawBuffers([g.COLOR_ATTACHMENT0,g.COLOR_ATTACHMENT1,g.COLOR_ATTACHMENT2]);g.frontFace(g.CCW);this.lightTextures();this.drawGeometry(this.programs.stone,this.base());
  bind(g,this.reflectTarget.t,9);const floorModel=model([0,FLOOR,-12],[-Math.PI/2,0,0],[65,65,1]);this.programs.floor.use({...this.base(),uModel:floorModel,uPreviousModel:floorModel,uReflectionEnabled:+this.effects.reflection,uReflectionMap:9,uReflectVP:this.reflectVP,uReflectSize:[this.reflectTarget.w,this.reflectTarget.h]});this.draw(this.meshes.plane);
  g.bindFramebuffer(g.READ_FRAMEBUFFER,this.sceneTarget.f);g.bindFramebuffer(g.DRAW_FRAMEBUFFER,this.opaqueDepth.f);g.blitFramebuffer(0,0,this.canvas.width,this.canvas.height,0,0,this.canvas.width,this.canvas.height,g.DEPTH_BUFFER_BIT,g.NEAREST);
  this.graph.mark('fire');this.setTarget(this.fireTarget);g.clearColor(0,0,0,0);g.clear(g.COLOR_BUFFER_BIT);this.drawFire(this.vp);
  this.graph.mark('atmosphere');this.setTarget(this.volumeTarget);g.disable(g.DEPTH_TEST);g.disable(g.BLEND);g.disable(g.CULL_FACE);bind(g,this.opaqueDepth.t,0);this.lightTextures();this.programs.volume.use({...this.base(),uDepth:0,uInverseVP:this.cameraState.inverseViewProjection,uSteps:this.effects.volume?this.profile.steps:1});if(this.effects.volume)this.full();else{g.clearColor(0,0,0,0);g.clear(g.COLOR_BUFFER_BIT);}
  const fireScreen=this.lights.slice(0,2).flatMap(l=>{const p=project(this.vp,l.position);return [p[0]*.5+.5,p[1]*.5+.5,Math.hypot(...l.position.map((v,i)=>v-this.camera[i])),1];});
  this.graph.mark('heat-and-transmission');this.setTarget(this.behindTarget);bind(g,this.sceneTarget.t,0);bind(g,this.fireTarget.t,1);bind(g,this.volumeTarget.t,2);bind(g,this.opaqueDepth.t,3);this.programs.composite.use({uScene:0,uFire:1,uVolume:2,uDepth:3,uResolution:[this.canvas.width,this.canvas.height],uTime:this.time,uFireScreen:this.effects.heat?fireScreen:fireScreen.map((v,i)=>i%4===2?1e6:v)});this.full();
  this.graph.mark('glass');g.bindFramebuffer(g.FRAMEBUFFER,this.sceneTarget.f);g.drawBuffers([g.COLOR_ATTACHMENT0]);copyColor(g,this.behindTarget,this.sceneTarget);this.setTarget(this.sceneTarget);g.frontFace(g.CCW);this.lightTextures();this.drawCards(this.vp,false,true);copyColor(g,this.sceneTarget,this.internalTarget);copyColor(g,this.behindTarget,this.sceneTarget);this.setTarget(this.sceneTarget);g.drawBuffers([g.COLOR_ATTACHMENT0,g.COLOR_ATTACHMENT1,g.COLOR_ATTACHMENT2]);bind(g,this.internalTarget.t,2);this.drawCards(this.vp,false,false);this.drawCardDepth();
  this.graph.mark('sparks');this.setTarget(this.particleTarget);g.clearColor(0,0,0,0);g.clear(g.COLOR_BUFFER_BIT);g.enable(g.DEPTH_TEST);g.depthMask(false);g.enable(g.BLEND);g.blendFunc(g.ONE,g.ONE);g.disable(g.CULL_FACE);this.programs.particles.use({uVP:this.vp,uTime:this.time,uDpr:this.dpr,uReduced:+this.reduced,uMotion:this.motion.velocity});g.bindVertexArray(this.sparkVao);g.drawArrays(g.POINTS,0,this.mobile?480:this.sparkCount);this.drawCalls++;g.depthMask(true);g.disable(g.BLEND);g.disable(g.DEPTH_TEST);
  this.graph.mark('optical-resolve');this.setTarget(this.resolvedTarget);bind(g,this.sceneTarget.t,0);bind(g,this.particleTarget.t,1);bind(g,this.sceneTarget.depth,2);bind(g,this.velocityTarget.t,3);bind(g,this.normalTarget.t,4);this.programs.resolve.use({uScene:0,uParticles:1,uDepth:2,uVelocity:3,uNormal:4,uResolution:[this.canvas.width,this.canvas.height],uFocusDistance:this.mobile?18.5:14.5,uQuality:this.profile.low?0:1,uMotionEnabled:+(this.historyValid&&this.profile.motion&&this.effects.motion),uShutter:Math.min(.4,.0042/Math.max(this.delta,.001))});this.full();
  this.graph.mark('bloom');let source=this.resolvedTarget;for(let i=0;i<this.blooms.length;i++){const[a,b]=this.blooms[i];this.setTarget(a);bind(g,source.t,0);this.programs.blur.use({uMap:0,uStep:[1/source.w,0],uExtract:+(i===0)});this.full();this.setTarget(b);bind(g,a.t,0);this.programs.blur.use({uMap:0,uStep:[0,1/a.h],uExtract:0});this.full();source=b;}
  this.graph.mark('flare-visibility');const flares=this.lights.slice(0,2).flatMap(l=>{const p=project(this.vp,l.position);return [p[0]*.5+.5,p[1]*.5+.5,p[2]*.5+.5,p[2]<1&&p[2]>-1?1:0];}),old=this.visibilities[this.visibilityIndex],next=this.visibilities[1-this.visibilityIndex];this.setTarget(next);bind(g,this.sceneTarget.depth,0);bind(g,old.t,1);this.programs.visibility.use({uDepth:0,uPrevious:1,uFlare:flares,uResolution:[this.canvas.width,this.canvas.height],uBlend:this.history.valid&&!this.paused&&!this.reduced?1-Math.exp(-this.delta*9):1});this.full();this.visibilityIndex=1-this.visibilityIndex;
  this.graph.mark('display');this.setTarget(null);bind(g,this.resolvedTarget.t,0);for(let i=0;i<5;i++)bind(g,this.blooms[i][1].t,i+1);bind(g,next.t,6);this.programs.output.use({uScene:0,uBloom0:1,uBloom1:2,uBloom2:3,uBloom3:4,uBloom4:5,uVisibility:6,uFlare:flares,uResolution:[this.canvas.width,this.canvas.height],uLensK:this.cameraState.lens.k,uAspect:this.cameraState.aspect,uExposure:.95,uBloomGain:this.effects.bloom?.78:0,uFlareGain:this.effects.flare?.44:0,uAberration:this.mobile?.12:.32,uAaStrength:this.profile.aaStrength});this.full();
  this.frames++;this.previousVP=this.vp.slice();this.previousTime=this.time;this.previousTravel=this.motion.travel;for(const c of this.renderCards){c.previousModel=c.model.slice();c.previousY=c.y;}this.history.commit(this.motion.travel);this.lastCpuMs=performance.now()-started;
 }
 preview(index){const g=this.gl,t=this.cards[index].demoTarget,data=this.artHdr?new Float32Array(t.w*t.h*4):new Uint8Array(t.w*t.h*4);this.setTarget(t);g.readPixels(0,0,t.w,t.h,g.RGBA,this.artHdr?g.FLOAT:g.UNSIGNED_BYTE,data);const cv=document.createElement('canvas');cv.width=t.w;cv.height=t.h;const ctx=cv.getContext('2d'),image=ctx.createImageData(t.w,t.h);for(let y=0;y<t.h;y++)for(let x=0;x<t.w;x++){const i=(y*t.w+x)*4,j=((t.h-1-y)*t.w+x)*4;for(let c=0;c<3;c++){let v=Math.max(0,data[i+c]/(this.artHdr?1:255));v=clamp(v*(2.51*v+.03)/(v*(2.43*v+.59)+.14),0,1);v=v<=.0031308?v*12.92:1.055*v**(1/2.4)-.055;image.data[j+c]=Math.round(v*255);}image.data[j+3]=255;}ctx.putImageData(image,0,0);this.setTarget(null);return cv.toDataURL('image/png');}
 inspect(){return {version:VERSION,ready:this.ready,api:'WebGL2',hdr:this.hdr,artHdr:this.artHdr,glassTransmission:!!this.internalTarget,fire:'gradient flow / shared light rig',frames:this.frames,drawCalls:this.drawCalls,position:this.motion.value,target:this.motion.target,hover:this.hover,quality:this.quality,reduced:this.reduced,width:this.canvas.width,height:this.canvas.height,chainCount:this.chainCount,chains:[chainOffset(this.motion.travel,-1),chainOffset(this.motion.travel,1)],cards:this.cards.map(c=>({index:c.index,y:c.y,screen:[((c.screen?.[0]??0)*.5+.5)*(this.width??0),(.5-(c.screen?.[1]??0)*.5)*(this.height??0)]})),occurrences:this.renderCards.map(c=>({key:c.key,index:c.index,y:c.y,visible:c.visible})),passes:this.graph.trace,historyValid:this.historyValid,historyReason:this.history.reason,reflection:'planar camera',probeReady:this.probeReady,shadowMaps:this.shadows?.length,geometryObjects:this.objects.length,attachmentBytes:this.pool.bytes+this.mediaPool.bytes,resolutionScale:this.dpr,antialiasing:'FXAA',aaStrength:this.profile?.aaStrength,capabilities:this.capabilities};}
 dispose(){const g=this.gl;this.cards.forEach(c=>{c.video?.pause();g.deleteTexture(c.label);if(c.videoTex)g.deleteTexture(c.videoTex);if(c.tex!==c.demoTarget?.t&&c.tex!==c.videoTex)g.deleteTexture(c.tex);});this.pool.dispose();this.mediaPool.dispose();this.instances?.dispose();new Set(Object.values(this.meshes)).forEach(m=>m.dispose());Object.values(this.programs).forEach(p=>p.dispose());g.deleteVertexArray(this.sparkVao);g.deleteBuffer(this.sparkBuffer);g.deleteFramebuffer(this.probeFbo);g.deleteRenderbuffer(this.probeDepth);g.deleteTexture(this.probe);g.deleteTexture(this.emptyProbe);g.deleteTexture(this.vistaTexture);}
}
