export class Program{
 constructor(gl,vs,fs){this.gl=gl;this.p=gl.createProgram();this.uniforms=new Map();for(const [type,src] of [[gl.VERTEX_SHADER,vs],[gl.FRAGMENT_SHADER,fs]]){const s=gl.createShader(type);gl.shaderSource(s,src);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s));gl.attachShader(this.p,s);gl.deleteShader(s);}gl.linkProgram(this.p);if(!gl.getProgramParameter(this.p,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(this.p));for(let i=0;i<gl.getProgramParameter(this.p,gl.ACTIVE_UNIFORMS);i++){const u=gl.getActiveUniform(this.p,i);this.uniforms.set(u.name.replace('[0]',''),{loc:gl.getUniformLocation(this.p,u.name),type:u.type,size:u.size});}}
 dispose(){this.gl.deleteProgram(this.p);}
 use(values={}){const g=this.gl;g.useProgram(this.p);for(const [name,v] of Object.entries(values)){const u=this.uniforms.get(name);if(!u)continue;const l=u.loc;switch(u.type){case g.FLOAT:u.size>1?g.uniform1fv(l,v):g.uniform1f(l,v);break;case g.INT:case g.BOOL:case g.SAMPLER_CUBE:case g.SAMPLER_2D_SHADOW:case g.SAMPLER_2D:u.size>1?g.uniform1iv(l,v):g.uniform1i(l,v);break;case g.FLOAT_VEC2:g.uniform2fv(l,v);break;case g.FLOAT_VEC3:g.uniform3fv(l,v);break;case g.FLOAT_VEC4:g.uniform4fv(l,v);break;case g.FLOAT_MAT4:g.uniformMatrix4fv(l,false,v);break;}}return this;}
}
export function mesh(g,d){const buffers=[];const vao=g.createVertexArray();g.bindVertexArray(vao);for(const [i,n,key] of [[0,3,'positions'],[1,3,'normals'],[2,2,'uvs']]){const b=g.createBuffer();buffers.push(b);g.bindBuffer(g.ARRAY_BUFFER,b);g.bufferData(g.ARRAY_BUFFER,new Float32Array(d[key]),g.STATIC_DRAW);g.enableVertexAttribArray(i);g.vertexAttribPointer(i,n,g.FLOAT,false,0,0);}if(d.surfaces){const b=g.createBuffer();buffers.push(b);g.bindBuffer(g.ARRAY_BUFFER,b);g.bufferData(g.ARRAY_BUFFER,new Float32Array(d.surfaces),g.STATIC_DRAW);g.enableVertexAttribArray(3);g.vertexAttribPointer(3,4,g.FLOAT,false,0,0);}const ib=g.createBuffer();buffers.push(ib);g.bindBuffer(g.ELEMENT_ARRAY_BUFFER,ib);g.bufferData(g.ELEMENT_ARRAY_BUFFER,new Uint32Array(d.indices),g.STATIC_DRAW);g.bindVertexArray(null);return {vao,count:d.indices.length,dispose(){g.deleteVertexArray(vao);buffers.forEach(b=>g.deleteBuffer(b));}};}
export function bind(g,t,unit){g.activeTexture(g.TEXTURE0+unit);g.bindTexture(g.TEXTURE_2D,t);}
export function target(g,w,h,hdr=true,depth=false){
 const f=g.createFramebuffer(),t=g.createTexture();bind(g,t,0);g.texImage2D(g.TEXTURE_2D,0,hdr?g.RGBA16F:g.RGBA8,w,h,0,g.RGBA,hdr?g.HALF_FLOAT:g.UNSIGNED_BYTE,null);for(const [key,v] of [[g.TEXTURE_MIN_FILTER,g.LINEAR],[g.TEXTURE_MAG_FILTER,g.LINEAR],[g.TEXTURE_WRAP_S,g.CLAMP_TO_EDGE],[g.TEXTURE_WRAP_T,g.CLAMP_TO_EDGE]])g.texParameteri(g.TEXTURE_2D,key,v);g.bindFramebuffer(g.FRAMEBUFFER,f);g.framebufferTexture2D(g.FRAMEBUFFER,g.COLOR_ATTACHMENT0,g.TEXTURE_2D,t,0);
 let dt=null;if(depth){dt=g.createTexture();bind(g,dt,0);g.texImage2D(g.TEXTURE_2D,0,g.DEPTH_COMPONENT24,w,h,0,g.DEPTH_COMPONENT,g.UNSIGNED_INT,null);g.texParameteri(g.TEXTURE_2D,g.TEXTURE_MIN_FILTER,g.NEAREST);g.texParameteri(g.TEXTURE_2D,g.TEXTURE_MAG_FILTER,g.NEAREST);g.texParameteri(g.TEXTURE_2D,g.TEXTURE_WRAP_S,g.CLAMP_TO_EDGE);g.texParameteri(g.TEXTURE_2D,g.TEXTURE_WRAP_T,g.CLAMP_TO_EDGE);g.framebufferTexture2D(g.FRAMEBUFFER,g.DEPTH_ATTACHMENT,g.TEXTURE_2D,dt,0);}
 if(g.checkFramebufferStatus(g.FRAMEBUFFER)!==g.FRAMEBUFFER_COMPLETE)throw Error('Framebuffer indisponível');
 return {f,t,depth:dt,w,h,dispose(){g.deleteFramebuffer(f);g.deleteTexture(t);if(dt)g.deleteTexture(dt);}};
}
export function imageTexture(g,image,srgb=true){const t=g.createTexture();bind(g,t,0);g.pixelStorei(g.UNPACK_FLIP_Y_WEBGL,true);g.texImage2D(g.TEXTURE_2D,0,srgb?g.SRGB8_ALPHA8:g.RGBA,g.RGBA,g.UNSIGNED_BYTE,image);g.generateMipmap(g.TEXTURE_2D);g.texParameteri(g.TEXTURE_2D,g.TEXTURE_MIN_FILTER,g.LINEAR_MIPMAP_LINEAR);g.texParameteri(g.TEXTURE_2D,g.TEXTURE_MAG_FILTER,g.LINEAR);g.texParameteri(g.TEXTURE_2D,g.TEXTURE_WRAP_S,g.CLAMP_TO_EDGE);g.texParameteri(g.TEXTURE_2D,g.TEXTURE_WRAP_T,g.CLAMP_TO_EDGE);const aniso=g.getExtension('EXT_texture_filter_anisotropic')||g.getExtension('WEBKIT_EXT_texture_filter_anisotropic');if(aniso){const max=g.getParameter(aniso.MAX_TEXTURE_MAX_ANISOTROPY_EXT)||1;g.texParameterf(g.TEXTURE_2D,aniso.TEXTURE_MAX_ANISOTROPY_EXT,Math.min(8,max));}return t;}
export async function loadImage(g,url){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),12000);let objectUrl;try{const response=await fetch(url,{signal:controller.signal});if(!response.ok)throw Error('Image HTTP '+response.status);objectUrl=URL.createObjectURL(await response.blob());const im=new Image();im.src=objectUrl;await im.decode();return imageTexture(g,im);}finally{clearTimeout(timer);if(objectUrl)URL.revokeObjectURL(objectUrl);}}
