import {Forge} from './engine.js';
import {CONTENT} from './content.js';
import {dragGesture} from './core.js';
const $=s=>document.querySelector(s),canvas=$('#scene'),dialog=$('#viewer');let forge=null,raf=0,last=0,pointer=null,active=0,pausedByDialog=false;
function list(){const host=document.createElement('div');host.className='gallery-list';CONTENT.projects.forEach((c,i)=>{const b=document.createElement('button');b.type='button';b.textContent=c.title;const hint=document.createElement('span');hint.textContent=c.kind==='demo'?'PRÉVIA VISUAL':c.kind.toUpperCase();b.append(hint);b.onclick=()=>show(i);host.append(b);});return host;}
function open(){if(!dialog.open){dialog.showModal();pausedByDialog=true;cancel();}}
function show(i){if(forge&&!forge.ready)return;const c=CONTENT.projects[i],host=$('#viewer-content');host.replaceChildren();const h=document.createElement('h2');h.id='viewer-title';h.textContent=c.title;
 const media=document.createElement(c.kind==='video'&&c.src?'video':'img');if(media.tagName==='VIDEO'){media.controls=true;media.playsInline=true;media.preload='metadata';media.src=c.src;if(c.poster)media.poster=c.poster;}else{media.alt=c.kind==='demo'?'Composição procedural de demonstração':c.title;if(c.kind==='image'&&c.src)media.src=c.src;else if(c.poster)media.src=c.poster;else if(forge)media.src=forge.preview(i);}
 const p=document.createElement('p');p.textContent=c.description;host.append(media,h,p);open();}
function close(){const v=dialog.querySelector('video');if(v)v.pause();dialog.close();pausedByDialog=false;last=performance.now();canvas.focus({preventScroll:true});}
$('#close').onclick=close;dialog.addEventListener('cancel',e=>{e.preventDefault();close();});dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)close();}});
$('#gallery').onclick=()=>{$('#viewer-content').replaceChildren();const h=document.createElement('h2');h.id='viewer-title';h.textContent='GALERIA';$('#viewer-content').append(h,list());open();};
function navigate(n){if(!forge?.ready||dialog.open)return;forge.motion.advance(n);forge.clear();$('#hint').textContent='CLIQUE PARA EXPLORAR';}
$('#next').onclick=()=>navigate(1);$('#previous').onclick=()=>navigate(-1);$('.brand').onclick=e=>{e.preventDefault();if(forge)forge.motion.reset();};
$('#quality').onclick=()=>{if(!forge)return;const options=['auto','low','high'];forge.quality=options[(options.indexOf(forge.quality)+1)%3];$('#quality').innerHTML=({auto:'AUTO',low:'LEVE',high:'ALTA'})[forge.quality]+' <span aria-hidden="true">◈</span>';forge.resize();};
$('#pause').onclick=()=>{if(!forge)return;forge.paused=!forge.paused;$('#pause').setAttribute('aria-pressed',String(forge.paused));$('#pause').textContent=forge.paused?'▷':'Ⅱ';$('#pause').setAttribute('aria-label',forge.paused?'Retomar animações':'Pausar animações');};
canvas.addEventListener('wheel',e=>{if(!forge?.ready||dialog.open||e.ctrlKey||e.metaKey)return;e.preventDefault();const d=Math.abs(e.deltaY)>Math.abs(e.deltaX)?e.deltaY:e.deltaX;const unit=e.deltaMode===1?16:e.deltaMode===2?innerHeight:1;navigate(d*unit/700);},{passive:false});
canvas.addEventListener('pointerdown',e=>{if(!forge?.ready||dialog.open||e.button!==0||!e.isPrimary)return;e.preventDefault();canvas.focus({preventScroll:true});pointer={id:e.pointerId,x:e.clientX,y:e.clientY,lastY:e.clientY,moved:false};canvas.setPointerCapture(e.pointerId);canvas.classList.add('dragging');document.body.classList.add('dragging');});
canvas.addEventListener('pointermove',e=>{if(!forge?.ready||dialog.open)return;if(pointer&&pointer.id===e.pointerId){if(dragGesture(e.clientX-pointer.x,e.clientY-pointer.y))pointer.moved=true;if(pointer.moved)forge.motion.advance(-(e.clientY-pointer.lastY)/240);pointer.lastY=e.clientY;}else{const hit=forge.point(e.clientX/innerWidth,e.clientY/innerHeight,e.timeStamp/1000);canvas.style.cursor=hit?'pointer':'grab';}});
canvas.addEventListener('pointerup',e=>{if(!pointer||pointer.id!==e.pointerId)return;const click=!pointer.moved;cancel();if(click){const hit=forge.pick(e.clientX/innerWidth,e.clientY/innerHeight);if(hit)show(hit.index);}});
function cancel(){const p=pointer;pointer=null;if(p&&canvas.hasPointerCapture(p.id))canvas.releasePointerCapture(p.id);canvas.classList.remove('dragging');document.body.classList.remove('dragging');forge?.clear();}
canvas.addEventListener('pointercancel',cancel);canvas.addEventListener('lostpointercapture',()=>{if(pointer)cancel();});canvas.addEventListener('pointerleave',()=>{if(!pointer)forge?.clear();});canvas.addEventListener('dragstart',e=>e.preventDefault());
canvas.addEventListener('keydown',e=>{if(!forge?.ready||dialog.open)return;if(['ArrowDown','ArrowUp','PageDown','PageUp','Home','Enter',' '].includes(e.key))e.preventDefault();if(['ArrowDown','PageDown'].includes(e.key))navigate(1);if(['ArrowUp','PageUp'].includes(e.key))navigate(-1);if(e.key==='Home')forge.motion.reset();if(e.key==='Enter'||e.key===' ')show(active);});
function fallback(err){console.warn('[BRAAZA]',err.message);cancelAnimationFrame(raf);canvas.hidden=true;$('#fallback').hidden=false;$('#fallback-list').append(list());$('#forge').classList.add('ready');$('#quality').disabled=true;$('#pause').disabled=true;}
function frame(now){raf=requestAnimationFrame(frame);const dt=Math.min((now-last)/1000,.04);last=now;if(document.hidden||pausedByDialog||forge.contextLost)return;forge.update(dt);forge.render();const best=forge.cards.reduce((a,c)=>Math.abs(c.y-5.1)<Math.abs(a.y-5.1)?c:a);if(active!==best.index){active=best.index;$('#status').textContent=CONTENT.projects[active].title;}}
async function start(){try{if(new URLSearchParams(location.search).has('no-webgl'))throw Error('Modo de compatibilidade');forge?.dispose();forge=new Forge(canvas);await forge.initialize();$('#pause').setAttribute('aria-pressed',String(forge.paused));$('#pause').textContent=forge.paused?'▷':'Ⅱ';$('#pause').setAttribute('aria-label',forge.paused?'Retomar animações':'Pausar animações');$('#forge').classList.add('ready');$('#loader').setAttribute('aria-hidden','true');last=performance.now();raf=requestAnimationFrame(frame);if(new URLSearchParams(location.search).has('debug')||window.__TEST__)window.__BRAAZA__={inspect:()=>forge.inspect(),get:()=>forge,show};}catch(e){fallback(e);}}
window.addEventListener('resize',()=>{try{forge?.resize();}catch(e){fallback(e);}});window.addEventListener('blur',cancel);document.addEventListener('visibilitychange',()=>{forge?.invalidateHistory('visibility');last=performance.now();if(document.hidden)cancel();});matchMedia('(prefers-reduced-motion: reduce)').addEventListener('change',e=>{if(forge){forge.reduced=e.matches;forge.clear();}});
canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();if(forge)forge.contextLost=true;cancel();});canvas.addEventListener('webglcontextrestored',()=>{cancelAnimationFrame(raf);start();});window.addEventListener('pagehide',()=>cancelAnimationFrame(raf));window.addEventListener('pageshow',e=>{if(e.persisted){last=performance.now();raf=requestAnimationFrame(frame);}});start();
