import {cardMatrix,unprojectCard,materialImpulse,backgroundTreatment} from './card-projection.js';
import {cardVertex,cardFragment,fullVertex,blurFragment,finishFragment} from '../render/card-material.js';
const damp=(a,b,k,dt)=>a+(b-a)*(1-Math.exp(-k*dt));
/** One WebGL context, shared by every tilted card. Native anchors retain navigation/focus. */
export class PerspectiveCards{
 constructor(host,settings={}){
  this.host=host;this.settings=settings;this.abort=new AbortController();this.frames=0;this.time=0;this.raf=0;this.dirty=true;this.last=performance.now();this.reduced=matchMedia('(prefers-reduced-motion: reduce)');this.cards=[...host.querySelectorAll('.perspective-card')].map((el,i)=>({el,face:el.querySelector('.card-face'),img:el.querySelector('.surface-image'),hover:0,goal:0,pointer:[.5,.5],target:[.5,.5],pulse:new Float32Array(32).fill(-100),slot:0,lastPoint:null,lastPulse:-1,texture:null,matrix:cardMatrix(),id:i}));
  if(!this.cards.length)return;
  this.canvas=document.createElement('canvas');this.canvas.className='card-optics';this.canvas.setAttribute('aria-hidden','true');this.canvas.hidden=true;host.prepend(this.canvas);
  const on=(e,n,f,o={})=>e.addEventListener(n,f,{...o,signal:this.abort.signal});
  on(document,'pointermove',e=>{this.eventPoint=[e.clientX,e.clientY];this.updatePointer(e);},{passive:true});
  on(host,'pointerleave',()=>{this.eventPoint=null;this.cards.forEach(c=>{c.goal=0;c.lastPoint=null});this.wake()});
  on(host,'focusin',()=>this.wake());on(host,'focusout',()=>this.wake());on(window,'scroll',()=>this.wake(),{passive:true});on(host,'scroll',()=>{this.dirty=true;this.wake()},{passive:true,capture:true});
  on(document,'visibilitychange',()=>document.hidden?this.sleep():this.wake());on(this.reduced,'change',()=>this.wake());
  on(this.canvas,'webglcontextlost',e=>{e.preventDefault();this.ready=false;this.sleep();host.classList.remove('cards-gl-ready');this.canvas.hidden=true;});
  on(this.canvas,'webglcontextrestored',()=>{this.pending=null;this.resources=[];this.programs=[];this.init();});
  this.resizeObserver=new ResizeObserver(()=>{this.dirty=true;this.wake()});this.resizeObserver.observe(host);this.cards.forEach(c=>this.resizeObserver.observe(c.el));
  this.intersection=new IntersectionObserver(es=>{this.visible=es[0].isIntersecting;if(this.visible)this.wake();else this.sleep()},{rootMargin:'160px'});this.intersection.observe(host);this.visible=true;
  this.resources=[];this.programs=[];this.applyTransforms();this.init();
 }
 compile(v,f){const g=this.gl,p=g.createProgram(),shaders=[];for(const[type,source]of[[g.VERTEX_SHADER,v],[g.FRAGMENT_SHADER,f]]){const s=g.createShader(type);g.shaderSource(s,source);g.compileShader(s);if(!g.getShaderParameter(s,g.COMPILE_STATUS))throw Error(g.getShaderInfoLog(s));g.attachShader(p,s);shaders.push(s);}g.linkProgram(p);for(const s of shaders)g.deleteShader(s);if(!g.getProgramParameter(p,g.LINK_STATUS))throw Error(g.getProgramInfoLog(p));this.programs.push(p);return{p,u:new Map};}
 uniform(program,name,value){const g=this.gl;let loc=program.u.get(name);if(loc===undefined){loc=g.getUniformLocation(program.p,name);program.u.set(name,loc);}if(loc===null)return;if(typeof value==='number'){g.uniform1f(loc,value);return;}if(value.length===16)g.uniformMatrix4fv(loc,false,value);else if(value.length===32)g.uniform4fv(loc,value);else if(value.length===2)g.uniform2fv(loc,value);else if(value.length===3)g.uniform3fv(loc,value);else if(value.length===4)g.uniform4fv(loc,value);}
 use(p,props={}){this.gl.useProgram(p.p);for(const[k,v]of Object.entries(props))this.uniform(p,k,v);}
 bindTexture(p,name,texture,slot){const g=this.gl;g.activeTexture(g.TEXTURE0+slot);g.bindTexture(g.TEXTURE_2D,texture);g.uniform1i(g.getUniformLocation(p.p,name),slot);}
 async init(){
  try{const g=this.gl=this.canvas.getContext('webgl2',{alpha:true,depth:false,stencil:false,premultipliedAlpha:true,antialias:false,powerPreference:'low-power'});if(!g)throw Error('WebGL2 unavailable');this.hdr=!!g.getExtension('EXT_color_buffer_float');this.linearFloat=!!g.getExtension('OES_texture_float_linear');
   this.faceProgram=this.compile(cardVertex,cardFragment);this.blurProgram=this.compile(fullVertex,blurFragment);this.finishProgram=this.compile(fullVertex,finishFragment);
   this.vao=g.createVertexArray();this.buffer=g.createBuffer();g.bindVertexArray(this.vao);g.bindBuffer(g.ARRAY_BUFFER,this.buffer);g.bufferData(g.ARRAY_BUFFER,new Float32Array([0,0,1,0,0,1,0,1,1,0,1,1]),g.STATIC_DRAW);g.enableVertexAttribArray(0);g.vertexAttribPointer(0,2,g.FLOAT,false,0,0);g.bindVertexArray(null);
   await Promise.all(this.cards.map(async c=>{await c.img.decode();if(this.disposed)return;const t=c.texture=g.createTexture();g.bindTexture(g.TEXTURE_2D,t);g.pixelStorei(g.UNPACK_FLIP_Y_WEBGL,false);g.texImage2D(g.TEXTURE_2D,0,g.RGBA,g.RGBA,g.UNSIGNED_BYTE,c.img);g.generateMipmap(g.TEXTURE_2D);g.texParameteri(g.TEXTURE_2D,g.TEXTURE_MIN_FILTER,g.LINEAR_MIPMAP_LINEAR);g.texParameteri(g.TEXTURE_2D,g.TEXTURE_MAG_FILTER,g.LINEAR);g.texParameteri(g.TEXTURE_2D,g.TEXTURE_WRAP_S,g.CLAMP_TO_EDGE);g.texParameteri(g.TEXTURE_2D,g.TEXTURE_WRAP_T,g.CLAMP_TO_EDGE);const a=g.getExtension('EXT_texture_filter_anisotropic');if(a)g.texParameterf(g.TEXTURE_2D,a.TEXTURE_MAX_ANISOTROPY_EXT,Math.min(4,g.getParameter(a.MAX_TEXTURE_MAX_ANISOTROPY_EXT)));}));
   if(this.disposed)return;this.ready=true;this.dirty=true;this.wake();
  }catch(e){this.fallback(e);}
 }
 fallback(e){this.ready=false;this.canvas.hidden=true;this.host.classList.remove('cards-gl-ready');console.warn('[DXT] Perspective cards use native fallback.',e.message);this.wake();}
 measure(){const h=this.host.getBoundingClientRect();this.origin=h;this.mobile=innerWidth<800;this.cards.forEach(c=>{const r=c.el.getBoundingClientRect();c.size=[c.el.clientWidth,c.el.clientHeight];c.center=[r.left-h.left+r.width/2,r.top-h.top+r.height/2];c.viewportCenter=[r.left+r.width/2,r.top+r.height/2];const parent=c.el.parentElement.getBoundingClientRect();c.clip=this.mobile?[parent.left-h.left,parent.top-h.top,parent.right-h.left,parent.bottom-h.top]:[0,0,h.width,h.height];});if(!this.ready)return;
  const ratio=Math.min(devicePixelRatio||1,this.settings.quality==='low'?1:1.4,Math.sqrt(2100000/(h.width*h.height))),w=Math.ceil(h.width*ratio),ht=Math.ceil(h.height*ratio);
  this.viewSize=[h.width,h.height];if(w===this.canvas.width&&ht===this.canvas.height&&!this.dirty)return;this.canvas.width=w;this.canvas.height=ht;this.releaseTargets();const add=(w,h)=>{const g=this.gl,t=g.createTexture(),f=g.createFramebuffer();g.bindTexture(g.TEXTURE_2D,t);g.texImage2D(g.TEXTURE_2D,0,this.hdr?g.RGBA16F:g.RGBA8,w,h,0,g.RGBA,this.hdr?g.HALF_FLOAT:g.UNSIGNED_BYTE,null);g.texParameteri(g.TEXTURE_2D,g.TEXTURE_MIN_FILTER,g.LINEAR);g.texParameteri(g.TEXTURE_2D,g.TEXTURE_MAG_FILTER,g.LINEAR);g.texParameteri(g.TEXTURE_2D,g.TEXTURE_WRAP_S,g.CLAMP_TO_EDGE);g.texParameteri(g.TEXTURE_2D,g.TEXTURE_WRAP_T,g.CLAMP_TO_EDGE);g.bindFramebuffer(g.FRAMEBUFFER,f);g.framebufferTexture2D(g.FRAMEBUFFER,g.COLOR_ATTACHMENT0,g.TEXTURE_2D,t,0);if(g.checkFramebufferStatus(g.FRAMEBUFFER)!==g.FRAMEBUFFER_COMPLETE)throw Error('Card framebuffer incomplete');const out={t,f,w,h};this.resources.push(out);return out;};this.scene=add(w,ht);this.a=add(Math.ceil(w/2),Math.ceil(ht/2));this.b=add(this.a.w,this.a.h);this.c=add(Math.ceil(w/4),Math.ceil(ht/4));this.d=add(this.c.w,this.c.h);this.dirty=false;
 }
 applyTransforms(){for(const c of this.cards){c.matrix=cardMatrix(c.hover,this.mobile);c.face.style.transform=`matrix3d(${c.matrix.join(',')})`;c.face.style.setProperty('--lift',c.hover);}}
 updatePointer(event){let found=false;for(const c of this.cards){if(!c.viewportCenter)continue;const q=unprojectCard(c.matrix,event.clientX-c.viewportCenter[0],event.clientY-c.viewportCenter[1]),uv=[q[0]/c.size[0]+.5,q[1]/c.size[1]+.5],inside=uv[0]>=0&&uv[0]<=1&&uv[1]>=0&&uv[1]<=1&&event.clientX-this.origin.left>=c.clip[0]&&event.clientX-this.origin.left<=c.clip[2]&&event.clientY-this.origin.top>=c.clip[1]&&event.clientY-this.origin.top<=c.clip[3];c.goal=inside?1:0;if(inside){found=true;c.target=uv;const now=event.timeStamp/1000;if(c.lastPoint&&now-c.lastPulse>.035&&!this.reduced.matches){const dt=now-c.lastPoint.t,speed=dt>0?Math.hypot(event.clientX-c.lastPoint.x,event.clientY-c.lastPoint.y)/dt:0,e=materialImpulse(speed);if(e){c.pulse.set([uv[0],uv[1],this.time,e],c.slot*4);c.slot=(c.slot+1)%8;c.lastPulse=now;}}c.lastPoint={x:event.clientX,y:event.clientY,t:now};}else c.lastPoint=null;}this.active=found;this.wake();}
 target(t){const g=this.gl;g.bindFramebuffer(g.FRAMEBUFFER,t?.f??null);g.viewport(0,0,t?.w??this.canvas.width,t?.h??this.canvas.height);}
 blur(from,to,step,extract){const g=this.gl;this.target(to);this.use(this.blurProgram,{uStep:step,uExtract:extract});this.bindTexture(this.blurProgram,'uImage',from.t,0);g.drawArrays(g.TRIANGLES,0,3);}
 frame(now){this.raf=0;if(this.disposed||document.hidden||!this.visible)return;const dt=Math.max(0,(now-this.last)/1000);this.last=now;this.time+=dt;let moving=false;
  if(this.dirty||!this.origin)this.measure();else{const rect=this.host.getBoundingClientRect(),dy=rect.top-this.origin.top;this.cards.forEach(c=>c.viewportCenter[1]+=dy);this.origin=rect;}
  for(const c of this.cards){const focused=c.el.matches(':focus-visible')||c.face.matches(':focus-visible');const goal=focused?1:c.goal;c.hover=this.reduced.matches?goal:damp(c.hover,goal,10,dt);c.pointer[0]=damp(c.pointer[0],c.target[0],14,dt);c.pointer[1]=damp(c.pointer[1],c.target[1],14,dt);moving ||= Math.abs(c.hover-goal)>.002||Math.abs(c.pointer[0]-c.target[0])>.002||Math.abs(c.pointer[1]-c.target[1])>.002;for(let i=0;i<8;i++)if(this.time-c.pulse[i*4+2]<2)moving=true;}
  this.applyTransforms();
  if(this.ready){try{const g=this.gl;this.target(this.scene);g.clearColor(0,0,0,0);g.clear(g.COLOR_BUFFER_BIT);g.disable(g.DEPTH_TEST);g.disable(g.CULL_FACE);g.enable(g.BLEND);g.blendFunc(g.ONE,g.ONE_MINUS_SRC_ALPHA);g.bindVertexArray(this.vao);
   const dominant=Math.max(0,...this.cards.map(c=>c.hover));for(const c of [...this.cards].sort((a,b)=>a.hover-b.hover)){if(c.viewportCenter[1]+c.size[1]<-150||c.viewportCenter[1]-c.size[1]>innerHeight+150)continue;const [dim,defocus]=backgroundTreatment(c.hover,dominant);const tint=c.el.dataset.tone==='ice'?[.35,.69,1.]:c.el.dataset.tone==='orange'?[1.,.29,.025]:[1.,.015,.055];this.use(this.faceProgram,{uSize:c.size,uCenter:c.center,uViewport:this.viewSize,uMatrix:c.matrix,uPointer:c.pointer,uHover:c.hover,uTime:this.time,uPulse:c.pulse,uDim:dim,uDefocus:defocus,uTint:tint,uBack:-3.4,uClip:c.clip,uRaster:[this.canvas.width,this.canvas.height]});this.bindTexture(this.faceProgram,'uImage',c.texture,0);g.drawArrays(g.TRIANGLES,0,6);this.uniform(this.faceProgram,'uBack',0);g.drawArrays(g.TRIANGLES,0,6);}
   g.bindVertexArray(null);g.disable(g.BLEND);this.blur(this.scene,this.a,[1/this.scene.w,0],1);this.blur(this.a,this.b,[0,1/this.a.h],0);this.blur(this.b,this.c,[2/this.b.w,0],0);this.blur(this.c,this.d,[0,2/this.c.h],0);this.target(null);this.use(this.finishProgram);this.bindTexture(this.finishProgram,'uImage',this.scene.t,0);this.bindTexture(this.finishProgram,'uGlow',this.b.t,1);this.bindTexture(this.finishProgram,'uAir',this.d.t,2);g.drawArrays(g.TRIANGLES,0,3);this.canvas.hidden=false;this.host.classList.add('cards-gl-ready');this.frames++;
  }catch(e){this.fallback(e);}}
  if(moving)this.raf=requestAnimationFrame(t=>this.frame(t));
 }
 wake(){if(!this.raf&&!this.disposed&&this.visible&&!document.hidden){this.last=performance.now();this.raf=requestAnimationFrame(t=>this.frame(t));}}
 sleep(){cancelAnimationFrame(this.raf);this.raf=0;}
 releaseTargets(){if(!this.gl)return;for(const t of this.resources){this.gl.deleteTexture(t.t);this.gl.deleteFramebuffer(t.f);}this.resources=[];}
 inspect(){return{ready:!!this.ready,frames:this.frames,cards:this.cards.length,hdr:this.hdr,scheduled:!!this.raf,projection:'shared physical perspective',hover:this.cards.map(c=>c.hover)};}
 dispose(){this.disposed=true;this.sleep();this.abort.abort();this.resizeObserver?.disconnect();this.intersection?.disconnect();this.releaseTargets();if(this.gl){this.cards.forEach(c=>this.gl.deleteTexture(c.texture));this.programs.forEach(p=>this.gl.deleteProgram(p));this.gl.deleteBuffer(this.buffer);this.gl.deleteVertexArray(this.vao);this.gl.getExtension('WEBGL_lose_context')?.loseContext();}this.canvas?.remove();}
}
